- finance/finance_view.xml
提交前:
未审核的会计凭证和审核完成的会计凭证不好区分。
提交后:
未审核的会计凭证和审核完成的会计凭证更容易区分。
--
> '设置财务凭证部分，如果未审核则列表页面整行显示蓝色。'

- finance/finance.py
---
科目叫账户会跟收付款账户混淆
凭证按id排序，新凭证在列表后面会计查起来不方便
提交前:
---
分类和账户上要求选择账户，逻辑混淆
提交后:
---
需要为分类和账户设置科目
--
> [IMP]finance 微小修正，凭证按时间逆序排列，分类和账户对应的科目标签修改

- core/core.py
- core/core_demo.xml
- core/core_view.xml
- core/security/groups.xml
- core/security/ir.model.access.csv
- money/other_money_order.py
- money/tests/test_money.py
- money/view/other_money_order_view.xml
---
其他收入和其他支出可选择服务
提交前:
---
其他收入和其他支出只能管理到类别级别
提交后:
---
能够在其他收入、其他支出上选择服务，并带出服务对应的收支类别，以便管理非主营业务非库存管理商品的采购和销售记录。
--
> [UPD]其他收入和其他支出可选择服务 #317

- province_city_county/partner_address.xml
- province_city_county/province_city_county.py
- province_city_county/tests/test_city_county.py
---
联系人地址没有拼接省市县
提交前:
---
联系人地址只有详细地址，没有拼接省市县
提交后:
---
联系人地址拼接省市县和详细地址，并且一个地址不能被多个联系人选到
--
> [FIX]联系人地址要拼接省市县，并且一个地址不能被多个联系人选到

- buy/buy.py
- buy/buy_view.xml
- buy/security/groups.xml
- core/core_view.xml
- core/security/groups.xml
- finance/balance_sheet.py
- money/generate_accounting.py
- money/view/go_live_order_view.xml
- sell/sell_view.xml
---
由于采购订单默认未选择按入库结算，粉刷匠发现付款时带不出入库单（对应的结算单），而且对账单里也没有此项
提交前:
---
采购订单和采购入库单默认按付款进度结算
提交后:
---
采购订单和采购入库单默认按收货结算
--
> [Fix] #400 #401 采购应默认按入库结算

- finance/data/finance_data.xml
- money/other_money_order.py
- money/partner.py
- money/report/bank_statements.py
- money/view/other_money_order_view.xml
- money/view/partner_view.xml
---
期初余额输入后可以生成凭证，并可被后续的收付款核销掉
提交前:
---
前一个版本删去了期初余额表的录入界面
提交后:
---
增加了期初余额科目，使用方法如下：
- 客户的界面增加 应收期初字段，输入后生成结算单和会计凭证，修改收入科目为期初科目后记账
- 供应商的界面增加 应付期初字段，输入后生成结算单和会计凭证，修改采购科目为期初科目后记账
- 新建一个其他收入类型叫资金期初，科目指向期初科目 资金账户的期初由其他收入方式录入
--
> [ADD] 更新期初输入方式

- buy/buy_view.xml
- warehouse/view/warehouse_view.xml
- warehouse/warehouse_order.py
---
提交前:
---
入库单和发货单审核时报错：源库位和目标库位不能一样
提交后:
---
入库单和发货单审核时正常
--
> [IMP]解决入库单和发货单审核时提示源库位和目标库位不能一样的错误

- warehouse/warehouse_move_line.py
---
下拉批次时显示仓库
由于批次下拉字段使用了parent.warehouse_id 作为条件，而这个条件有时不生效，导致非当前发货仓库的批次也可以下拉到，这样就给用户选择错误的机会。下拉时显示仓库虽然有些傻，但是避免出错。
提交前:
---
下拉批次时只显示批次和剩余数量
提交后:
---
显示 批次 仓库 剩余数量
--
> [IMP]下拉时显示批次所在库位

- buy/buy_view.xml
- partner_address/partner_address.py
- partner_address/partner_address.xml
- partner_address/tests/test_partner_address.py
- sell/sell.py
- sell/sell_view.xml
- sell/tests/test_sell.py
> [IMP]调整采购和销售中单据下方排版，发货单上的地址和手机应为选择联系人（默认联系人在业务伙伴窗体中设置），然后自动带出地址和手机。

- sell/__openerp__.py
---
提交前:
---
没安装partner_address时，销货订单上会报找不到contact属性
提交后:
---
--
> [FIX]sell增加对partner_address的依赖

- buy/buy.py
- buy/tests/test_buy.py
- sell/sell.py
- sell/tests/test_sell.py
- warehouse/warehouse_move_line.py
---
提交前:
---
[FIX]采购和销售订单行上的数量乘以含税单价，价税合计相差0.01分，审核可以通过。 #537
提交后:
---
价税合计 = 数量 * 含税价，
采购（销售）金额 = 价税合计- 税额
--
> [FIX]采购和销售订单行上的数量乘以含税单价，价税合计相差0.01分，审核可以通过。 #537

- buy/buy.py
- buy/tests/test_buy.py
- buy/tests/test_report.py
- money/view/money_order_view.xml
> [ADD] 在商品上勾选‘每批号数量为1’;在采购入库单里有相同的几个商品输入同一个批号可以保存审核 #543

- buy/buy.py
- sell/sell.py
- sell/tests/test_sell.py
---
提交前:
---
只安装销售而不安装采购模块时发货单上选择产品   带不出单价
提交后:
---
只安装销售而不安装采购模块时发货单上选择产品   可以带出单价
--
> [FIX]解决只安装销售而不安装采购模块时发货单上选择产品带不出单价的bug

- finance/trial_balance.py
> 科目余额表生成错误，结算本月 把本月期初的数据生成的数据的期间写成上月 =-= (代码重构引起sorry)

- buy/models/buy_receipt.py
- goods/goods.py
- sell/models/sell_delivery.py
- sell/models/sell_order.py
---
提交前:
---
订单审核时，生成的销货单，联系人、地址、电话为空
提交后:
---
订单审核时，生成的销货单，默认为订单中的数据
--
> [IMP]订单审核时生成销货单时，联系人、地址、电话从订单中获取,以及代码重构，以适合扩展算法

- core/models/goods.py
---
提交前:
---
help=u'1个辅助单位等于多少计量计量单位的数量，如1箱30个苹果，这里输入30')
提交后:
---
help=u'1个辅助单位等于多少计量单位的数量，如1箱30个苹果，这里就输入30')
--
> 修改商品单位 转化率 提示文字

- warehouse/goods.py
---
提交前:
---
提交后:
---
辅助数量显示正常
--
> [FIX] 内部移库后，移出库的产品余额报表辅助数量为0

- auto_backup/backup_scheduler.py
---
例如 用 supervision 启动Odoo,  由于 HOME 和 HOMEPATH  变量都不存在, 使得 os.environ.get('HOME','') or os.environ.get('HOMEPATH','') 返回的值类型为 'NoneType' 与 str 类型 的字串 无法相加
给 get 方法一个默认值, 确保 方法返回的是 str 类型,
提交前:
---
  File "/xxxxxx/xxxxxx_addons/auto_backup/backup_scheduler.py", line 48, in 
    addons_path = (os.environ.get('HOME') or os.environ.get('HOMEPATH')) + '/DBbackups'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
提交后:
---
--
例如 用 supervision 启动Odoo,  由于 HOME 和 HOMEPATH  变量都不存在, 使得 os.environ.get('HOME','') or os.environ.get('HOMEPATH','') 返回的值类型为 'NoneType' 与 str 类型 的字串 无法相加
> 少数场景中, 环境变量HOME 和 HOMEPATH 并不存在

- web_export_view_good/view/web_export_view.xml
---
父菜单错误，还没依赖。
提交前:
---
提示：
ParseError: "External ID not found in the system: report.reporting_menuitem" while parsing /Users/mac/developWork/odoo/osbzr/gooderp_addons/web_export_view_good/view/web_export_view.xml:30, near 
```xml
<menuitem id="report_template_action_menu" action="report_template_action" parent="report.reporting_menuitem" sequence="10"/>
```
提交后:
---
bug fix
--
> web_export_view_good 报表模板菜单的新建．

- gooderp_statistics/__openerp__.py
> 	模块依赖错误,导致创建数据库时公司的 start_date 字段找不到

- fixed_header/static/src/js/fixed_header.js
---
修正js：将执行锁定表头代码移至父类方法返回的promise对象的done回调匿名函数中。
提交前:
---
混动列表，可正常锁定表头；
提交后:
---
混动列表，可正常锁定表头，功能并无变化；
--
> 修正固定表头js部分写法

- buy/views/buy_receipt_view.xml
- sell/models/sell_delivery.py
- sell/views/sell_view.xml
---
实际上仓库中该产品充足，但移库单、其他出库单等的出库明细行上产品批号下拉为空
提交前:
---
实际上仓库中该产品充足，但移库单、其他出库单等的出库明细行上产品批号下拉为空
提交后:
---
实际上仓库中该产品充足，移库单、其他出库单等的出库明细行上产品批号可查看
--
> [FIX]修复实际上仓库中该产品充足但移库单、其他出库单等的出库明细行上产品批号下拉为空的问题

- buy/models/buy_order.py
- buy/views/buy_order_view.xml
---
提交前:
---
提交后:
---
在购货订单清单界面的右上角可以输入商品编号或名称，选择商品搜索项，即可以将包含此商品的购货订单筛选出来。
再次以高级搜索的方式，搜索另一个商品，系统会将两次搜索作并集（and)处理，也就是说可以搜出同时包含了这两个不同商品的订单！这种用法很有意义。
--
> 购货订单支持按商品搜索

- money/money_order.py
> [FIX]继续修改ISSUE #1113：收付款单审核和反审核时都应该保持待核销行中金额、已核销金额、未核销金额不变

- web_dashboard_open_action/README.rst
- web_dashboard_open_action/__init__.py
- web_dashboard_open_action/__manifest__.py
- web_dashboard_open_action/static/src/css/web_dashboard_open_action.css
- web_dashboard_open_action/static/src/js/web_dashboard_open_action.js
- web_dashboard_open_action/static/src/xml/web_dashboard_open_action.xml
- web_dashboard_open_action/views/templates.xml
仪表板中的列表没有直接跳转回原列表视图的功能，如果需要修改过滤选项或者回到原列表视图需要再通过主页或APP菜单路径跳转。
提交前:
---
提交后:
---
在仪表板的每个列表区块右上角最小化按钮左边增加一个最大化按钮，点击此按钮即可直接跳转至原列表视图。
--
> 仪表板列表右上角增加跳转至原始列表视图的按钮

- good_process/static/src/js/good_process.js
本次提交合并增加的功能或解决的问题：审批过程中点击‘拒绝’按钮报js错误
---
提交前:
---
Uncaught ReferenceError: message is not defined
http://127.0.0.1:8066/good_process/static/src/js/good_process.js:49
回溯:
ReferenceError: message is not defined
at Object.<anonymous> (http://127.0.0.1:8066/good_process/static/src/js/good_process.js:49:47)
at Object.<anonymous> (http://127.0.0.1:8066/web/static/lib/jquery/jquery.js:3276:89)
at fire (http://127.0.0.1:8066/web/static/lib/jquery/jquery.js:3119:58)
at Object.fireWith [as resolveWith] (http://127.0.0.1:8066/web/static/lib/jquery/jquery.js:3231:49)
at Object.deferred.(anonymous function) (http://127.0.0.1:8066/web/static/lib/jquery/jquery.js:3321:62)
at fire (http://127.0.0.1:8066/web/static/lib/jquery/jquery.js:3119:58)
at Object.fireWith [as resolveWith] …
> bugfix 审批过程中点击‘拒绝’按钮报js错误

- warehouse_wave/report/report.xml
> [FIX] 修复打印拣货单，按格子号排序了，但是商品数量没有排序的bug

- finance/data/finance_data.xml
- finance/models/res_config.py
---
提交前:
---
使用 record 方式 内置的默认值 与 ir_values.set_deaulf(0 设置的默认值 不兼容， 造成 相同的默认值存在 2条记录， 会在ir_values.get_default() 调用时， 报 singleon 错误
提交后:
---
--
> 修正 内置默认值设置

- web_export_view_good/static/src/js/web_export_view_good.js
---
解决导出Excel表格浮点数报错的问题
如果浮点数中包含货币符号，则会报错
```
Uncaught Error: '570.00 ¥' 不是正确的浮点数
http://localhost:8069/web/static/src/js/framework/formats.js:146
追溯:
Error: '570.00 ¥' 不是正确的浮点数
at Object.parse_value (http://localhost:8069/web/static/src/js/framework/formats.js:146:23)
at String.<anonymous> (http://localhost:8069/web_export_view_good/static/src/js/web_export_view_good.js:47:45)
at Function.each (http://localhost:8069/web/static/lib/jquery/jquery.js:383:58)
at HTMLTableRowElement.<anonymous> (http://localhost:8069/web_export_view_good/static/src/js/web_export_view_good.js:36:15)
at Function.each (http://localhost:8069/web/static/lib/jquery/jquery.js:383:58)
at compute_main_data (http://localhost:8069/web_export_view_good/static/src/js/web_export_view_good.js:29:7)
at …
```
> fix export money symbol

- buy/models/buy_order.py
- good_process/models/mail_thread.py
- sell/models/sell_order.py
---
提交前:
---
1 购货订单设置了审批流程， 购货订单反审核后不需要审批
2 入库单设置了审批流程，入库单反审核时报错“审批后才能确认”
提交后:
---
1 购货订单反审核后需要重新审批
2 入库单能够反审核
--
> [FIX]采购、销售订单反审核时重新加入审批流程，及解决反审核入库单报错的bug

- home_page/static/src/css/home_page.css
- home_page/static/src/js/home_page.js
- home_page/static/src/xml/homepage.xml
---
完善主页关键指标中按钮的布局，使之根据屏幕大小，自动排列
提交前:
---
提交后:
---
--
> 完善主页关键指标中按钮的布局，使之根据屏幕大小，自动排列

- goods/models/goods.py
- goods/tests/test_goods.py
---
属性名称里不需要显示属性类别，以免冗余
提交前:
---
短袖衬衫 颜色：白 尺码：XL
提交后:
---
短袖衬衫 白 XL
--
> [IMP]属性名称里不显示属性类别

- goods/view/goods_view.xml
- money/models/money_order.py
---
提交前:
---
已有核销金额的采购入库单等可以被反审核，导致核销金额不对应等问题。
提交后:
---
已有核销金额的结算单不允许删除！
--
人生第一个提交  谢谢~！
> 添加限制 已有核销金额的结算单不允许删除
