osbzr/gooderp_addons

- warehouse/warehouse.py
File "/opt/odoo/gooderp/gooderp_addons/warehouse/warehouse.py", line 66, in name_get
res.append((warehouse.id, '[{}]{}'.format(warehouse.code, warehouse.name)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
> 解决一处Unicode编码报错

- money/tests/test_money.py
http://com.osbzr.net:9001/p/pep8lab
> [FMT] PEP8 Format..

- finance/finance.py
http://com.osbzr.net:9001/p/pep8lab
> [FMT] PEP8 Format

- buy/buy_view.xml
- buy/report/supplier_statements.py
- buy/report/supplier_statements_view.xml
- money/money_order.py
- money/view/money_order_view.xml
- money/wizard/partner_statements_wizard.py
- sell/report/customer_statements.py
- sell/report/customer_statements_view.xml
> [ADD]业务伙伴对账单收付款金额未考虑整单折扣。添加相关业务逻辑 #177

- core/core.py
- sell/sell_data.xml
- sell/sell_view.xml
- sell/tests/test_sell.py
> [fix]销售订单，发货单，上的单价为只读。

- .gitignore
- staff/__openerp__.py
- staff/staff.py
- staff/staff_contract.py
- staff/tests/test_staff.py
> pep8 for module staff

- buy/buy.py
- core/core_view.xml
- sell/sell_view.xml
> [fix]销售单上的单价改为隐藏，添加被覆盖掉的税率字段

- buy/buy.py
- buy/tests/test_buy.py
- sell/sell.py
> [fix]#286购货订单，数量和单价不能录入负数，审核报错

- buy/buy_view.xml
> [add]入库单按收获结算这个字段为真，隐藏本次付款、结算账户两个字段

- finance/finance.py
- finance/finance_conf.xml
- money/money_order.py
- money/view/money_order_view.xml
> [fix]会计模块去掉无用字段，#285采购退货单审核时不会报错余额不足

- mobile/controllers/main.py
- mobile/data/test_demo.xml
- mobile/html/index.html
- mobile/mobile.markdown
- mobile/mobile_view.py
- mobile/static/src/css/index.css
- mobile/static/src/js/component.js
- mobile/static/src/js/index.js
- warehouse/data/warehouse_data.xml
- warehouse/report/report_base.py
> 添加mobile视图的表头固定，以及合计行

- staff/__init__.py
- staff/__openerp__.py
- staff/mail.py
- staff/mail_data.xml
> [ADD]员工生日时会收到祝福消息

- core/core_view.xml
- sell/sell.py
- warehouse/warehouse_move.py
> [add]扫码创建订单行带出仓库和单价，出库单审核报错bug修复

- staff/mail.py
- staff/tests/test_staff.py
> [FIX]修改发送员工生日信息方法bug，增加测试用例

- buy/report/buy_summary_goods.py
- buy/report/buy_summary_partner.py
- sell/report/sell_summary_goods.py
- sell/report/sell_summary_partner.py
- sell/report/sell_summary_staff.py
> [FIX]解决销售（采购）汇总表中bug

- buy/tests/test_report.py
---
解决上次提交代码没覆盖到的问题
提交前:
---
采购汇总表的代码有两行没覆盖到
提交后:
---
采购汇总表的代码均覆盖到
--
> [FIX]修改采购汇总表测试代码，以提高覆盖率

- finance/trial_balance.py
- finance/trial_balance.xml
---
总账和明细账的输出结果优化
提交前:
---
提交后:
---
--
> [FIX]总账和明细账打印的一些文字修正，余额计算还有问题

- finance/trial_balance.py
> [fix]py文件加u

- finance/finance_conf.xml
- finance/finance_view.xml
- finance/security/groups.xml
> [fix] fix issues

- province_city_county/province_city_county.py
---
改进地址信息的书面
提交前:
---
提交后:
---
1级 -省/市/区 
2级 -市  
3级 -区/市/县 
--
>  改进 字段说明信息

- buy/buy.py
- finance/balance_sheet.xml
- home_page/home_page.py
> 中文字符加u,	资产负债表wizard弹窗按钮文字应该是资产负债表。

- finance/balance_sheet.py
- finance/finance.py
- goods/view/goods_view.xml
- province_city_county/security/ir.model.access.csv
---
默认日期取的是服务器启动日期，错误
提交前:
---
默认日期取的是服务器启动日期
提交后:
---
默认日期取的是当前日期
--
> [FIX]会计凭证默认日期不应当为2016.05.23,应默认为当前日期 #323

- finance/__init__.py
- finance/__openerp__.py
- finance/data/finance_data.xml
- finance/finance.py
- finance/report/__init__.py
- finance/report/report.py
- finance/report/report_voucher.xml
- finance/tests/finance_demo.xml
- finance/tests/test_finance.py
---
提交前:
---只能录入会计凭证
提交后:
---
会计凭证可以打印啦！>v<
--
> [add]会计凭证打印

- finance/balance_sheet.py
- finance/data/finance_data.xml
- finance/finance.py
- finance/tests/finance_demo.xml
---
提交前:
---
提交后:
---
会计科目表模板( 小企业会计准则2011)
--
> 会计科目表模板( 小企业会计准则2011)

- buy/buy.py
- money/money_order.py
> [fix]采购订单反审核生成的付款单自动删除 #284

- core/core_view.xml
> [add]允许修改公司logo #346

- finance/trial_balance.py
---
科目明细账中，每一个凭证明细行输出的余额不对
提交前:
---
科目明细账中，每一个凭证明细行输出的余额不对
提交后:
---
科目明细账中，每一个凭证明细行的余额修改为上一个余额 + 借方 - 贷方
--
> [FIX]科目明细账凭证明细行输出的余额不对 #327

- core/core_view.xml
- finance/finance_conf.xml
- finance/report/report_voucher.xml
- sell/sell.py
> [fix]会计凭证打印没对齐,合计分列显示

- warehouse/inventory.py
> [fix]仓库管理部分盘点如果没有盘盈和盘亏整个盘点单不能完成 #344

- province_city_county/partner_address.xml
---
省市县设置为必输
提交前:
---
由于县可以不选，最后拼接的地址里会出现false，同时数据的规范性也不能保证
提交后:
---
全部必输
--
> [FIX] #356

- buy/buy_view.xml
- finance/report/report_voucher.xml
- sell/sell_view.xml
- warehouse/warehouse_move_line.py
> [fix]销售发货退货界面添加chat_message,会计凭证打印调整

- finance/balance_sheet.py
---
利润行计算逻辑
提交前:
---
利润 = 收入+成本
提交后:
---
利润 = 收入 - 成本
--
> [FIX] #366 利润表利润行计算

- finance/finance.py
> 会计科目编号和名称同时显示和可供搜索

- buy/buy_view.xml
> [FIX] #371 入库单结算方式与订单保持一致

- core/core.py
- finance/finance.py
> [FIX]修正冲红情况（负）转大写出错**

- .gitignore
- finance/trial_balance.py
> [fix]本年利润计算问题

- finance/balance_sheet.py
- finance/data/finance_data.xml
- finance/trial_balance.xml
- finance/wizard/checkout_wizard.py
> [FIX]修正 累计折旧 余额方向：贷，修正资产负债表 固定资产账面价值（累计折旧 贷方造成），科目余额表列表增加本年累计

- staff/__openerp__.py
- staff/staff.py
- staff/staff.xml
> [del]去掉省市县模块

- warehouse/report/stock_balance.py
> [FIX]sql影响库存余额表

- warehouse/report/stock_balance.py
> [FIX]考虑勾选又取消勾选的产品

- finance/trial_balance.py
> [FIX] 上年度余额(本年度期初)不应记入本年累计

- core/core.py
- core/core_view.xml
- sell/sell_demo.xml
> [add]定价策略添加开始日期

- finance/__openerp__.py
- finance/data/finance_data.xml
- finance/finance.py
- finance/finance_view.xml
- finance/tests/finance_demo.xml
- finance/tests/test_finance.py
- money/data/money_data.xml
> [修改]会计凭证录入明细行中不允许新建会计科目，统一在会计科目菜单中处理。

- finance/tests/test_report.py
- finance/trial_balance.py
- finance/trial_balance.xml
---
科目明细账，科目总账 从单一科目统计修改为科目范围统计。
提交前:
---
科目明细账，科目总账 只能查询  单一科目 
提交后:
---
科目明细账，科目总账 可以查询  科目范围。
--
> 【修改】科目明细账，科目总账 从单一科目统计修改为科目范围统计。

- finance/__init__.py
- finance/__openerp__.py
- finance/finance.py
- finance/finance_conf.xml
- finance/res_config.py
- finance/res_config_view.xml
---
提交前:
---
凭证日期的默认取值：当前日期
提交后:
---
凭证日期的默认取值根据设置：取当前日期或上一凭证日期
--
> [ADD] 增加新建会计凭证:凭证日期的默认取值设置：当前日期或上一凭证日期。

- finance/balance_sheet.py
- finance/finance.py
---
提交前:
---
凭证日期的默认取值：当前日期
提交后:
---
凭证日期的默认取值根据设置：取当前日期或上一凭证日期
--
> [FIX]会计期间排序，资产负债表及利润表过滤掉没结账的期间。

- finance/balance_sheet.py
- finance/balance_sheet.xml
- finance/data/finance_data.xml
- finance/finance.py
- finance/res_config.py
- finance/res_config_view.xml
- finance/trial_balance.py
- finance/trial_balance.xml
- finance/wizard/checkout_wizard.py
> [FIX]修改凭证列表排序，增加设置是否能查看未结账期间资产及利润表（交用户选择）。

- finance/trial_balance.py
---
提交前:
---
提交后:
---
科目明细账计算 测试OK!
--
> [FIX]科目明细账计算。

- core/core.py
> [FIX]类别和可选值不允许重名

- core/core.py
- money/data/money_data.xml
- money/generate_accounting.py
> [IMP]类别和可选值名称和类型必输，会计科目未配置报错更明确，采购暂估用材料采购科目

- sell/sell.py
> [fix]调拨单不判断价格策略

- sell/sell.py
> [fix]只有销售发货退货检查定价策略

- sell/sell.py
- sell/sell_view.xml
- warehouse/data/warehouse_demo.xml
- warehouse/warehouse_move.py
- warehouse/warehouse_move_line.py
> [IMP]移库单行源和目标仓库都必输，销售部分修改

- buy/buy.py
- buy/buy_demo.xml
- goods/goods_demo.xml
- sell/sell.py
- sell/sell_data.xml
- sell/sell_demo.xml
- sell/tests/test_sell.py
- sell/wizard/sell_order_detail_wizard.py
- warehouse/data/warehouse_demo.xml
- warehouse/inventory.py
- warehouse/tests/test_inventory.py
- warehouse/tests/test_move_line.py
- warehouse/tests/test_production.py
- warehouse/tests/test_warehouse_order.py
- warehouse/view/warehouse_view.xml
- warehouse/warehouse_move.py
- warehouse/warehouse_move_line.py
---
提交前:
---
提交后:
---
移库单行源和目标仓库都和移库单保持一致
--
> [IMP]移库单行源和目标仓库都和移库单保持一致

- buy/buy_view.xml
- warehouse/action/warehouse_action.xml
- warehouse/data/warehouse_demo.xml
- warehouse/inventory.py
- warehouse/view/inventory_view.xml
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
- warehouse/warehouse_move_line.py
- warehouse/warehouse_order.py
> [IMP]去掉移库单行上的源库位和目的库位。

- finance/wizard/checkout_wizard.py
> [fix] finance 变量未定义错误

- buy/security/groups.xml
- core/core.py
- core/security/groups.xml
- finance/security/groups.xml
- goods/security/groups.xml
- home_page/security/groups.xml
- money/security/groups.xml
- sell/security/groups.xml
- staff/security/groups.xml
- warehouse/security/groups.xml
> [IMP]名称字段必输，管理员有所有权限

- buy/buy.py
- buy/buy_demo.xml
- buy/buy_view.xml
- buy/tests/test_buy.py
- sell/__openerp__.py
- sell/sell.py
- sell/sell_demo.xml
- sell/sell_view.xml
- sell/tests/test_sell.py
- warehouse/data/warehouse_demo.xml
> [IMP]去掉销售和采购模块中明细行上的源库位和目的库位。

- warehouse/report/stock_balance.py
> [fix]库存余额表bug修复

- finance/res_config_view.xml
> [IMP]会计默认设置窗体上的按钮为英文 #424

- warehouse/view/warehouse_view.xml
> [IMP]仓库单据列表显示出入库的仓库

- warehouse/report/stock_transceive_view.xml
> [fix]商品收发明细表字段顺序调整

- buy/wizard/buy_order_track_wizard.py
- sell/wizard/sell_order_track_wizard.py
---
销售报表没有减去退货的 #411
提交前:
---
提交后:
---
--
> [FIX]销售和采购跟踪表退货时数量等取反

- buy/report/buy_order_detail.py
- buy/report/buy_order_detail_view.xml
- buy/report/buy_summary_goods.py
- buy/report/buy_summary_goods_view.xml
- buy/report/buy_summary_partner.py
- buy/report/buy_summary_partner_view.xml
- buy/security/ir.model.access.csv
- buy/wizard/buy_order_detail_wizard.py
- sell/report/sell_order_detail.py
- sell/report/sell_order_detail_view.xml
- sell/report/sell_summary_goods.py
- sell/report/sell_summary_goods_view.xml
- sell/report/sell_summary_partner.py
- sell/report/sell_summary_partner_view.xml
- sell/report/sell_summary_staff.py
- sell/report/sell_summary_staff_view.xml
- sell/security/ir.model.access.csv
- sell/tests/test_report.py
- sell/wizard/sell_order_detail_wizard.py
---
销售报表没有减去退货的 #411
提交前:
---
提交后:
---
--
> [FIX]采购和销售汇总表和明细表考虑退货的情况；解决汇总表上查看明细时的bug

- goods/view/goods_view.xml
---
提交前:
---
在商品里只能按品名搜索
提交后:
---
在商品里能按品名、编号、类别搜索
--
> [IMP]修改Issues：在商品里只能按品名搜索 #417

- buy/buy_view.xml
- sell/sell_view.xml
- warehouse/action/warehouse_action.xml
- warehouse/view/warehouse_view.xml
- warehouse/warehouse_move_line.py
> [fix] 解决批次显示问题

- buy/buy_view.xml
- finance/balance_sheet.py
- finance/tests/test_report.py
- finance/trial_balance.py
- finance/trial_balance.xml
- goods/view/goods_view.xml
- sell/sell_view.xml
- sell/tests/test_report.py
> [IMP]能够在科目明细账里查看到每一条的明细 #360

- warehouse/tests/test_move_line.py
> [fix] ci fail

- finance/finance.py
> [fix]新建凭证时检查会计期间

- money/generate_accounting.xml
- money/money_order.py
- money/tests/test_money.py
> [IMP]类别里的科目除属性类型外均为必填项，如为空，在付款时会提示错误。 #399

- buy/tests/test_buy.py
- core/core.py
- core/core_view.xml
- finance/balance_sheet.py
- goods/goods.py
- goods/goods_demo.xml
- goods/view/goods_view.xml
- money/generate_accounting.xml
- sell/tests/test_sell.py
- warehouse/tests/test_warehouse.py
- warehouse/warehouse_move.py
---
提交前:
---
只支持产品属性的扫码出入库
提交后:
---
增加支持产品的扫码出入库
--
> [IMP]扫码可支持扫产品的条码 #420

- buy/buy.py
- buy/buy_data.xml
- buy/buy_view.xml
- buy/security/ir.model.access.csv
- buy/tests/test_buy.py
> [ADD]采购调整单及测试

- buy/buy_view.xml
- sell/sell_view.xml
- warehouse/menu/warehouse_menu.xml
> [IMP] 采购收货、销售出库也该显示在仓库菜单下 #449

- buy/buy.py
- buy/buy_view.xml
- goods/view/goods_view.xml
> [IMP]维护商品供货价格 #338 #349

- buy/security/ir.model.access.csv
> [fix]ci warning, add access

- buy/buy.py
- buy/tests/test_buy.py
> [IMP]采购调整单：调整后数量与已入库数量相等时，删除产生的入库单分单

- buy/buy.py
- buy/buy_view.xml
- buy/tests/test_buy.py
- sell/security/ir.model.access.csv
- sell/sell.py
- sell/sell_data.xml
- sell/sell_view.xml
- sell/tests/test_sell.py
> [ADD]销售调整单界面、逻辑及测试用例；增加test_buy_adjust_line #381

- core/core.py
- core/tests/test_core.py
- sell/tests/test_sell.py
> 把原来的test都完善了一下

- README.md
---
1.增加步骤说明
提交前:
---
1.缺少一个步骤 切换到gooderp_addons
提交后:
---
1.增加一个步骤的说明 切换到gooderp_addons
--
> 修改README，增加说明

- warehouse/data/copy_move_line.xml
> [fix]修正tree_view的sum错开一列

- buy/buy.py
- buy/buy_demo.xml
- buy/tests/test_buy.py
- goods/goods_demo.xml
- sell/sell.py
- sell/sell_demo.xml
- sell/tests/test_sell.py
- warehouse/warehouse_move_line.py
> [IMP]采购和销售模块里由含税价格和税率计算不含税价格 #466

- buy/buy.py
- buy/tests/test_buy.py
- sell/sell.py
- sell/tests/test_sell.py
> [IMP]采购和销售的单据明细行中产品数量和单价都不能小于0

- sell/tests/test_sell.py
- warehouse/warehouse_move.py
> [fix]单价字段修改

- buy/buy_view.xml
- finance/finance_view.xml
- money/view/money_order_view.xml
- money/view/other_money_order_view.xml
- money/view/reconcile_order_view.xml
- money/wizard/partner_statements_wizard_view.xml
- sell/sell_view.xml
- warehouse/view/warehouse_view.xml
> [IMP]供应商和客户在资金和仓库单据中只能选择，不能打开和新建

- finance/finance.py
- finance/wizard/checkout_wizard.py
- mobile/mobile_view.py
- staff/mail.py
- staff/staff.py
- warehouse/report/stock_balance.py
- warehouse/report/stock_transceive.py
---
提交前:
---
不能反结账！
if period_id.is_closed:
raise except_orm(u'错误', u'此会计期间已关闭')
else:
提交后:
---
可以反结账
--
> [FIX]不能反结账！

- money/money_order.py
- money/view/money_order_view.xml
> [ADD]invoice增加发票号和审核反审核按钮

- warehouse/warehouse_move_line.py
> [fix]move_line的日期和move的日期保持一致

- buy/buy_view.xml
- core/core_view.xml
- goods/view/goods_view.xml
- money/view/money_order_view.xml
- sell/sell_view.xml
> [IMP]为core模块中主数据、buy、sell、money模块增加search视图

- sell/sell.py
- sell/tests/test_report.py
- warehouse/goods.py
- warehouse/tests/test_report.py
- warehouse/warehouse_move_line.py
> [FIX]解决warehouse中test fail,已没有问题

- money/partner.py
- sell/sell.py
- sell/tests/test_report.py
- sell/tests/test_sell.py
- sell/wizard/popup_wizard.py
> [FIX]自动生成盘盈单逻辑修改，解决sell模块ci报错的问题

- sell/tests/test_report.py
> [FIX]sell_test

- core/core_view.xml
- money/generate_accounting.xml
- money/view/money_order_view.xml
- money/view/money_transfer_order_view.xml
- money/view/other_money_order_view.xml
- money/view/reconcile_order_view.xml
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
> [ADD]money、warehouse模块增加search 视图，组装拆卸单和库存调拨还没加

- buy/buy_view.xml
- buy/report/buy_payment.py
- buy/report/buy_payment_view.xml
- buy/tests/test_report.py
- buy/wizard/buy_payment_wizard.py
- buy/wizard/buy_payment_wizard_view.xml
- finance/balance_sheet.xml
- finance/finance_conf.xml
- sell/report/sell_receipt.py
- sell/report/sell_receipt_view.xml
- sell/report/sell_top_ten.py
- sell/report/sell_top_ten_view.xml
- sell/sell_view.xml
- sell/tests/test_report.py
- sell/wizard/sell_receipt_wizard.py
- sell/wizard/sell_receipt_wizard_view.xml
- sell/wizard/sell_top_ten_wizard.py
- sell/wizard/sell_top_ten_wizard_view.xml
- warehouse/view/inventory_view.xml
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
> [ADD]收款付款一览表、销量前十报表wizard增加仓库过滤条件，简化采购和销售报表的test

- money/view/money_order_view.xml
- sell/tests/test_report.py
- sell/wizard/popup_wizard.py
- warehouse/tests/test_report.py
---
提交前:
---
提交后:
---
提高覆盖率
--
> [IMP]增加发货单缺货向导测试用例，增加其他报表wizard上默认日期的测试

- sell/sell.py
- sell/wizard/popup_wizard.py
- warehouse/wizard/stock_transceive_wizard.py
> [add]商品收发明细表添加title带上起止日期

- warehouse/warehouse_move.py
---
提交前:
---
扫码入库时数量增加，而辅助单位数量却没增加
提交后:
---
扫码入库时数量增加，辅助单位数量也随之增加
--
> [FIX]扫码入库时数量增加，而辅助单位数量却没增加

- money/other_money_order.py
- money/security/groups.xml
- money/tests/test_money.py
- money/tests/test_report.py
- money/view/other_money_order_view.xml
> [IMP]其他收入支出单上增加税率和税，并加上税组

- finance/data/finance_data.xml
> [FIX]按金税三期要求修改或增加部分科目。

- sell/wizard/popup_wizard.py
> [fix]先审核生成的入库单，在审核当前出库单

- finance/finance.py
- finance/finance_view.xml
> [ADD] 会计凭证无massage #512

- goods/view/goods_view.xml
- warehouse/report/report_base.py
- warehouse/report/stock_transceive.py
- warehouse/tests/test_report.py
> 修复报表行数太多的时候右上角切换框消失的 bug

- money/other_money_order.py
> little fix: change description of other pay and other get

- buy/buy_view.xml
- sell/report/sell_summary_goods.py
- sell/report/sell_summary_goods_view.xml
- sell/report/sell_summary_partner.py
- sell/report/sell_summary_partner_view.xml
- sell/report/sell_summary_staff.py
- sell/report/sell_summary_staff_view.xml
- sell/sell_view.xml
- warehouse/warehouse_move_line.py
---
提交前:
---
对销售退货单计算销售毛利时，成本为0，导致毛利计算错误
提交后:
---
销售毛利计算正确
--
> [IMP]解决采购入库单和销售退货单的成本为0问题，销售汇总表增加销售毛利的统计

- sell/report/sell_order_detail.py
> [FIX] SQL fail

- buy/__openerp__.py
- core/__openerp__.py
- money/other_money_order.py
- money/tests/test_money.py
- money/tests/test_report.py
- sell/__openerp__.py
- staff/__openerp__.py
---
提交前:
---
提交后:
---
--
… in other money order line
> [FIX]core depends module mail;change calculation method of tax amount in other money order line

- money/money_transfer_order.py
- warehouse/warehouse_move.py
> [fix]其他收支单审核按钮bug修复，未找到产品的报错优化

- warehouse/__openerp__.py
> [FIX] warehouse depends docx

- finance/balance_sheet.py
> [FIX]利润表计算有误 (只有费用34000)

- buy/report/supplier_statements.py
- buy/report/supplier_statements_view.xml
- buy/tests/test_supplier_statements.py
- sell/report/customer_statements.py
- sell/report/customer_statements_view.xml
- sell/tests/test_report.py
> [FIX]客户和供应商对账单，及测试

- finance/balance_sheet.py
- finance/finance.py
- finance/trial_balance.py
---
提交前:
---
帐簿菜单进去的没有 期间及科目的默认值
提交后:
---
会计账簿向导输入参数给默认值 
--
> 会计账簿向导输入参数给默认值 #533

- finance/balance_sheet.py
- finance/finance.py
- finance/wizard/checkout_wizard.py
> [FIX]会计-默认设置里勾选是否重置凭证号后，不能月末结账；

- core/security/groups.xml
- finance/__openerp__.py
- finance/balance_sheet.py
- finance/finance.py
- finance/trial_balance.py
- home_page/__openerp__.py
- home_page/home_page.py
- home_page/static/src/js/home_page.js
> 直接给管理员用户增加技术特性权限组

- asset/data/asset_data.xml
- asset/view/asset.xml
> [ADD] 固定资产菜单调整 #562 ;固定资产反审核无效 #564

- finance/finance.py
- finance/finance_view.xml
> 带摘要和自动借贷调平 #552

- money/view/money_order_view.xml
> [ADD]资金模块也需要客户和供应商菜单 fix #566

- goods/goods.py
> [fix]属性ean搜索 全匹配

- asset/asset.py
- money/generate_accounting.py
- money/tests/test_invoice.py
- money/tests/test_money.py
> [IMP]有其他模块生成的会计凭证直接审核 #534

- buy/__openerp__.py
- buy/buy.py
- buy/buy_view.xml
- buy/tests/test_buy.py
- buy/tests/test_report.py
- buy/tests/test_supplier_statements.py
- sell/tests/test_report.py
- sell/tests/test_sell.py
- warehouse/__openerp__.py
- warehouse/tests/test_goods.py
- warehouse/tests/test_inventory.py
- warehouse/tests/test_move_line.py
- warehouse/tests/test_production.py
- warehouse/tests/test_report.py
- warehouse/tests/test_warehouse.py
- warehouse/tests/test_warehouse_order.py
- warehouse/view/warehouse_view.xml
- warehouse/warehouse_order.py
> [ADD]采购入库单审核时生成凭证 #532

- finance/tests/finance_demo.xml
- sell/sell.py
- sell/tests/test_sell.py
> [FIX]发货单生成的源单和收款都取发货单日期 #529

- buy/buy.py
- warehouse/warehouse_order.py
> [ADD] 有其他模块生成的会计凭证直接审核 #534

- buy/wizard/buy_payment_wizard.py
- sell/wizard/sell_receipt_wizard.py
> [FIX]采购收款一览表和销售收款一览表应显示退货库位 #589

- money/generate_accounting.py
- money/money_order.py
- money/money_transfer_order.py
- money/other_money_order.py
- money/partner.py
- money/tests/test_money.py
- money/view/money_order_view.xml
- money/view/money_transfer_order_view.xml
- money/wizard/bank_statements_wizard.py
- money/wizard/other_money_statements_wizard.py
- money/wizard/partner_statements_wizard.py
---
收付款单增加 折扣科目字段，用于记录付款和核销的差异 代码及测试已完成
转账单增加 折扣金额和折扣科目字段，逻辑代码还存在问题
提交前:
---
提交后:
---
--
> [ADD] 收付款单、转账单增加 折扣科目字段，用于记录付款和核销的差异 #574

- buy/buy.py
- buy/report/buy_order_detail.py
- buy/tests/test_buy.py
- buy/tests/test_report.py
- buy/wizard/buy_order_detail_wizard.py
- buy/wizard/buy_order_track_wizard.py
- buy/wizard/buy_payment_wizard.py
- buy/wizard/buy_summary_goods_wizard.py
- buy/wizard/buy_summary_partner_wizard.py
- sell/report/sell_order_detail.py
- sell/sell.py
- sell/tests/test_report.py
- sell/tests/test_sell.py
> [FIX]采购订单和入库单生成的付款单需要审核 #588

- buy/buy.py
- sell/sell.py
- sell/wizard/popup_wizard.py
- sell/wizard/sell_order_detail_wizard.py
- sell/wizard/sell_order_track_wizard.py
- sell/wizard/sell_receipt_wizard.py
- sell/wizard/sell_summary_goods_wizard.py
- sell/wizard/sell_summary_partner_wizard.py
- sell/wizard/sell_summary_staff_wizard.py
- sell/wizard/sell_top_ten_wizard.py
> [IMP]给每个字段增加 help 属性 #549：增加销售模块help及修改采购模块

- core/core_view.xml
- core/security/groups.xml
- home_page/home_page.xml
> [FIX]home_page change make upgrade dump

- core/core_view.xml
> [FIX]menu name

- gooderp_statistics/__init__.py
- gooderp_statistics/__openerp__.py
- gooderp_statistics/controllers/__init__.py
- gooderp_statistics/controllers/main.py
- gooderp_statistics/static/src/js/main.js
- gooderp_statistics/views/web_need.xml
> [ADD]statistics

- money/money_order.py
> [ADD] 资金-客户/供应商列表上的应收金额和明细的应该金额不相符 #605

- finance/finance.py
- finance/tests/test_report.py
- sell/sell.py
---
提交前:
---
提交后:
---
--
[ADD] 凭证号增加的属性 #606
> [FIX] 客户信用额度管控 #587 不更新信用额度的值

- buy/buy.py
- finance/finance_conf.xml
- finance/finance_view.xml
- finance/security/groups.xml
- money/generate_accounting.xml
- money/view/money_order_view.xml
- money/view/money_transfer_order_view.xml
- sell/sell.py
- sell/sell_view.xml
- sell/tests/test_sell.py
- warehouse/warehouse_move_line.py
> [FIX]bug:采购和销售明细行上价税合计的计算没有考虑折扣额，及修改test

- asset/asset.py
- buy/wizard/buy_payment_wizard.py
- sell/wizard/sell_receipt_wizard.py
> [FIX]修改bug:清理固定资产时产生的其他收入单name为PAY,实际应为GET，及审核时产生支出单name修改

- sell/sell.py
- sell/tests/test_sell.py
> [FIX] 客户信用额度，为0不考虑额度问题；比较时应减去 本次收款

- asset/__openerp__.py
- asset/asset.py
- asset/data/asset_demo.xml
- asset/tests/__init__.py
- asset/tests/test_asset.py
> [FIX]已审核/已清理的固定资产不允许删除,新建固定资产已审核已折旧，可以删除； #579

- finance/data/finance_export_template_data.xml
- finance/wizard/checkout_wizard.py
- web_export_view_good/controllers/controllers.py
> [FIX]按年重置凭证号，某区间无凭证的情况下上一凭证号的查找。

- core/core_view.xml
- core/static/src/css/style.css
- core/static/src/js/core.js
- warehouse/static/src/js/warehouse_widget.js
> 在新建状态下扫码自动保存、给按钮支持 default_focus 属性

- finance/tests/finance_demo.xml
- money/generate_accounting.xml
- money/other_money_order.py
- money/tests/test_money.py
- money/view/other_money_order_view.xml
> [ADD] 其他收支单行添加过滤条件、onchange_partner 修改及测试；

- report_docx/report/report_docx.py
> 自动将报表打印中的 False 变成，且支持 selection 的实际值

- report_docx/report/report_docx.py
> 可以直接在 word 上写 many2one 字段

- buy/tests/test_buy.py
- buy/tests/test_report.py
- money/money_order.py
- money/tests/test_money.py
- sell/tests/test_sell.py
> [ADD] 同一个业务伙伴不能有两张未审核的收付款 #626

- finance/__init__.py
- finance/__openerp__.py
- finance/security/ir.model.access.csv
- finance/voucher_template.py
- finance/voucher_template.xml
- warehouse/production.py
> 增加凭证模板功能 #410

- report_docx/report/report_docx.py
> 会自动转换报表的时间为当前选择的时区时间

- money/generate_accounting.py
> [FIX]清理固定资产收入（其他收入单）生成的税额是销项税应在贷方 #625

- web_export_view_good/static/src/js/web_export_view_good.js
> [IMP]导出列表的操作时间放在最后两列

- goods/goods.py
- goods/view/goods_view.xml
> [FIX]主数据-商品-条形码需要添加重复限制 #629，属性条码加一个label

- report_docx/report/report_docx.py
> 修复返回全为空的问题

- finance/__openerp__.py
- finance/finance.py
- finance/security/ir.model.access.csv
- finance/wizard/__init__.py
- finance/wizard/issue_cost_wizard.py
- finance/wizard/issue_cost_wizard.xml
> 月末结账前生成发出成本结转凭证 #584

- asset/asset.py
- asset/data/asset_data.xml
- asset/data/asset_demo.xml
- asset/view/asset.xml
---
根据师兄codereview优化asset模块代码
提交前:
---
提交后:
---
--
> [IMP]Improve asset module and resolve conflict

- asset/__openerp__.py
- asset/asset.py
- asset/view/asset.xml
- asset/view/asset_action.xml
- asset/view/asset_menu.xml
> [FIX]asset模块：拆分函数 create_depreciation，menu和action分别存放一个文件

- asset/view/asset.xml
- asset/view/asset_action.xml
> [FIX]xml记录顺序引起的CI出错

- web_export_view_good/controllers/controllers.py
> 列表导出excel前台没反应，后台报错 #653

- finance/__init__.py
- finance/__openerp__.py
- finance/finance_view.xml
- finance/issue_cost_wizard.py
- finance/issue_cost_wizard.xml
- finance/security/groups.xml
- finance/wizard/__init__.py
- finance/wizard/checkout_wizard.py
> 	[bug fix 漏洞修改]月末结账前生成发出成本结转凭证 #584

- finance/issue_cost_wizard.py
- finance/issue_cost_wizard.xml
> [bug fix 漏洞修改]发出成本表的发出成本 应和会计凭证中的保持一致。，

- asset/asset.py
> 资产折旧后看不到折旧明细 #649

- staff/mail.py
---
提交前:
---
test fail key error : mail.group
提交后:
---
test不报错
--
> [FIX]8.0升级到10.0,staff模块中需要将mail.group改成mail.channel

- money/tests/test_money.py
- money/tests/test_reconcile_order.py
> [FIX] fix money test error

- demo/__openerp__.py
- home_page/__openerp__.py
- sell/__openerp__.py
- warehouse/tests/__init__.py
- warehouse/tests/test_production.py
- web_export_view_good/tests/__init__.py
> [Fix]暂时去掉BOM的test

- buy/tests/test_buy.py
- sell/tests/test_sell.py
> [FIX]修改buy模块test fail

- asset/asset.py
- buy/buy.py
- goods/goods.py
- sell/sell.py
- staff/staff.py
- warehouse/inventory.py
- warehouse/production.py
- warehouse/warehouse_move_line.py
- warehouse/wizard/lot_track_wizard.py
- warehouse/wizard/stock_transceive_wizard.py
- web_export_view_good/controllers/controllers.py
> [FIX]各模块中onchange函数去掉@api.one

- warehouse/tests/__init__.py
- warehouse/tests/test_report.py
> [FIX]CI Fail

- finance/static/src/xml/base.xml
- warehouse/data/copy_move_line.xml
- warehouse/static/src/js/warehouse_widget.js
> [ADD] One2many tree 复制 按钮修改，需要修改逻辑

- report_docx/report/ir_report.py
- report_docx/report/report_docx.py
> [FIX]report_docx 报错，现在还是取不到数据

- buy/buy.py
- buy/tests/test_buy.py
- sell/sell.py
- sell/tests/test_sell.py
> [IMP]拿回调整单测试用例，修改one2many字段增加value的方法。增加其他测试用例

- report_docx/report/report_docx.py
> [FIX] 打印 出错

- demo/__openerp__.py
> [REM]tree_zero_dispaly_blank not work yet

- sell/report/sell_order_detail_view.xml
- sell/wizard/sell_order_detail_wizard.py
- warehouse/action/warehouse_action.xml
- warehouse/report/lot_status_view.xml
- warehouse/report/lot_track_view.xml
- warehouse/report/stock_balance_view.xml
- warehouse/report/stock_transceive_view.xml
> [ADD] change view type: from graph to pivot

- finance/static/src/xml/base.xml
- home_page/home_page.py
- home_page/static/src/js/home_page.js
- home_page/static/src/xml/homepage.xml
- num_to_china/static/src/js/num_to_china.js
> home_page模块10.0代码重构，number_to_china 代码迁移到10

- finance/report/report.py
> [FIX]change pool to env

- buy/buy.py
- sell/sell.py
> [FIX]修改购货订单收货状态计算方法bug，及销货订单相应修改

- money/tests/test_money.py
> [UPD] 完善测试用例，提高 money 模块覆盖率

- goods/view/goods_view.xml
> [UPD] 商品 form 显示异常，去掉多余 group

- buy/report/buy_order_detail_view.xml
- buy/report/buy_order_track_view.xml
- buy/report/buy_payment_view.xml
- buy/report/buy_summary_goods_view.xml
- buy/report/buy_summary_partner_view.xml
- buy/report/supplier_statements_view.xml
- buy/wizard/supplier_statements_wizard_view.xml
- finance/trial_balance.xml
- money/report/bank_statements_view.xml
- money/view/partner_view.xml
- sell/report/customer_statements_view.xml
- sell/report/sell_order_detail_view.xml
- sell/report/sell_order_track_view.xml
- sell/report/sell_receipt_view.xml
- sell/report/sell_summary_goods_view.xml
- sell/report/sell_summary_partner_view.xml
- sell/report/sell_summary_staff_view.xml
- sell/wizard/customer_statements_wizard_view.xml
- warehouse/report/stock_transceive_view.xml
---
浏览器报terp-stock_zoom 找不到
提交前:
---
提交后:
---
换成fa-search
--
> [FIX]查看明细按钮

- warehouse/production.py
- warehouse/tests/__init__.py
- warehouse/tests/test_production.py
> 修复组装、拆卸单直接报错的bug

- home_page/static/src/js/home_page.js
> 首页代码重构引起的报表部分bug fix

- buy/buy.py
- buy/tests/test_buy.py
- buy/wizard/buy_payment_wizard.py
- buy/wizard/buy_payment_wizard_view.xml
> [IMP]buy 模块代码优化（根据师兄codereview 修改意见）

- web_export_view_good/__openerp__.py
- web_export_view_good/controllers/controllers.py
- web_export_view_good/static/src/js/web_export_view_good.js
- web_export_view_good/static/src/xml/web_export_view_template.xml
---
提交前:
---是不能用的，因为前端的变化
提交后:
---现在可以在每个tree视图的 import 后面找到 导出Excel 按钮 选择要导出的记录然后点击 导出Excel 就可以得到具有一定格式的 excel 文件
--
> 原web_export_view_good 模块10.0迁移工作。(目前的打印在每个tree视图的 import后面)

- asset/view/asset.xml
- finance/balance_sheet.xml
- finance/trial_balance.xml
---
#[](url)
提交前:
--
提交后:
---
--
）
> 弹出窗口中出现保存 ，取消的按钮（实际上是不需要的。

- buy/report/supplier_statements.py
- money/report/bank_statements.py
- money/wizard/bank_statements_wizard.py
- money/wizard/partner_statements_wizard.py
- sell/report/customer_statements.py
> [ADD] 现金银行对账单行数过多会死循环；客户对账单、供应商对账单也做了相应的修改 #658

- buy/buy.py
- sell/report/sell_summary_goods.py
- sell/report/sell_summary_partner.py
- sell/report/sell_summary_staff.py
- sell/sell.py
- warehouse/warehouse_move_line.py
> [FIX]销售汇总表（按商品）毛利计算存在异常 #688，及wh_move_line上选择产品后计算成本的修改

- web_export_view_good/controllers/controllers.py
- web_export_view_good/static/src/js/web_export_view_good.js
- web_export_view_good/static/src/xml/web_export_view_template.xml
> 	1.解决 web_export_view_good 模块和系统导出xls 冲突 ，和修正 2.导出xls 在部分视图不显示的bug 3.导…  … …出文件名为中文的报错bug 修复。

- asset/asset.py
- buy/buy.py
- buy/report/supplier_statements.py
- buy/report/supplier_statements_view.xml
- buy/tests/test_buy.py
- buy/tests/test_supplier_statements.py
- finance/finance.py
- money/generate_accounting.py
- money/home_page_data.xml
- money/money_order.py
- money/partner.py
- money/report/bank_statements.py
- money/report/bank_statements_view.xml
- money/tests/test_money.py
- money/view/money_order_view.xml
- sell/report/customer_statements.py
- sell/report/customer_statements_view.xml
- sell/sell.py
- sell/tests/test_report.py
- warehouse/warehouse_move.py
---
凭证不平也能审核
提交前:
---
凭证不平也能审核
提交后:
---
报错
--
> [FIX]凭证有效性检查放在审核方法里，去掉所有源单字样

- buy/wizard/buy_order_detail_wizard.py
- buy/wizard/buy_order_track_wizard.py
- buy/wizard/buy_payment_wizard.py
- buy/wizard/buy_summary_goods_wizard.py
- buy/wizard/buy_summary_partner_wizard.py
- finance/balance_sheet.py
- finance/trial_balance.py
- finance/wizard/checkout_wizard.py
- money/wizard/other_money_statements_wizard.py
- sell/wizard/sell_order_detail_wizard.py
- sell/wizard/sell_order_track_wizard.py
- sell/wizard/sell_receipt_wizard.py
- sell/wizard/sell_summary_goods_wizard.py
- sell/wizard/sell_summary_partner_wizard.py
- sell/wizard/sell_summary_staff_wizard.py
- warehouse/wizard/lot_track_wizard.py
- warehouse/wizard/non_active_report_wizard.py
- warehouse/wizard/stock_transceive_wizard.py
> [ADD] 给 wizard 返回的报表添加  'limit': 65535

- web_export_view_good/controllers/controllers.py
- web_export_view_good/static/src/js/web_export_view_good.js
- web_menu_create/static/src/js/menu.js
> 1.调试代码删除2.web_export_view_good 适应 有 widegt = relation_sublist 的tree页面。

- finance/balance_sheet.py
- home_page/static/src/css/home_page.css
- home_page/static/src/js/home_page.js
- home_page/static/src/xml/homepage.xml
> 	home_page 10迁移后的首次美化。

- buy/buy.py
- finance/tests/test_finance.py
- warehouse/tests/test_inventory.py
- warehouse/tests/test_warehouse_order.py
> [FIX]解决warehouse及finance ci fail

- buy/buy.py
- buy/wizard/buy_payment_wizard.py
> [IMP]buy_payment_wizard函数太长拆分成多个函数，及buy_adjust_done函数的拆分等优化

- staff/staff.py
- staff/staff.xml
> 按金税三期个人所得税要求增加必需项

- buy/wizard/buy_order_track_wizard.py
> [IMP]优化buy_order_track_wizard.py，函数拆分，重复代码删除

- money/money_order.py
- money/money_transfer_order.py
- money/other_money_order.py
- money/partner.py
- money/wizard/partner_statements_wizard.py
> [UPD] money 模块代码优化，还有money_order.py 需要完善

- finance/tests/test_finance.py
> finance 测试数据。

- finance/tests/test_finance.py
- finance/wizard/checkout_wizard.py
- home_page/static/src/js/home_page.js
- home_page/static/src/xml/homepage.xml
- warehouse/tests/__init__.py
- warehouse/tests/test_finace.py
> 	1.finance 相关的测试。2.	迁移到10.0 某些方法不适用去除，相应的部分。（重新生成凭证编码.前后缀的方法导致的。）3.	home_page 样式 bug fix （在窗口缩小到一定比例会有错位）

- asset/asset.py
- asset/data/asset_demo.xml
- asset/tests/test_asset.py
- finance/tests/finance_demo.xml
> [ADD]增加asset.py测试代码，审核、反审核，固定资产清理、变更、折旧

- .travis.yml
- gooderp_statistics/__openerp__.py
> [ADD]new lib

- report_docx/models/ir_actions.py
- report_docx/report/report_docx.py
- report_docx/views/ir_actions.xml
> 添加odoo打印的pdf支持

- money/generate_accounting.py
- money/money_order.py
- money/tests/test_invoice.py
- money/tests/test_money.py
>  [ADD] 添加测试数据，提高 money 模块覆盖率。

- .travis.yml
> [FIX]change lib python-ooxml

- finance/data/finance_voucher_data.xml
- finance/report/report.py
- finance/tests/test_finance.py
- finance/tests/test_report.py
- finance/tests/test_trial_balance.py
- sell/tests/__init__.py
- sell/tests/test_finance.py
- warehouse/tests/__init__.py
- web_export_view_good/controllers/controllers.py
- web_export_view_good/static/src/js/web_export_view_good.js
- web_export_view_good/tests/__init__.py
- web_export_view_good/tests/test_web_export_view.py
> finance test

- asset/asset.py
- asset/tests/test_asset.py
> [ADD]asset.py中引入固定资产的测试

- warehouse/tests/__init__.py
- warehouse/tests/test_non_active_report.py
- warehouse/wizard/non_active_report_wizard.xml
> [ADD] warehouse 呆滞料报表及向导 添加测试数据提高覆盖率

- warehouse/production.py
- warehouse/tests/test_production.py
> [ADD] 添加 warehouse/组装拆卸单 的测试数据并修改代码写法问题，提高测试覆盖率

- finance/tests/test_finance.py
- sell/tests/test_finance.py
> finance  issue_cost_wizard 测试

- partner_address/partner_address.xml
---
供货商联系人地址栏改为选填项
提交前:
---
供货商联系人地址栏为必填项
#729 
提交后:
---
供货商联系人地址栏为选填项
--
修改供货商联系人地址栏必填的问题
> #729  Update partner_address.xml 

- auto_backup/__openerp__.py
- auto_backup/ir.model.access.csv
> [Add]csv for db backup access

- backend_theme/static/src/less/app_drawer.less
> theme 模块 菜单背景路径错误（忘记修改了）

- auto_backup/__manifest__.py
- auto_backup/backup_data.xml
- auto_backup/bkp_conf_view.xml
- auto_backup/i18n/zh_CN.po
> [IMP]auto_backup 粉刷匠修改部分字符

- money/generate_accounting.py
- money/report/bank_statements.py
- money/tests/test_money.py
- money/tests/test_report.py
- partner_address/tests/test_partner_address.py
> [ADD] 添加 money/generate_accounting 测试数据，提高覆盖率

- sell/tests/test_sell.py
- warehouse/production.py
- warehouse/tests/test_production.py
- warehouse/tests/test_warehouse_order.py
> [FIX]提高覆盖率：warehouse_order.py,production.py

- finance/tests/test_finance.py
- finance/tests/test_report.py
- finance/wizard/checkout_wizard.py
- money/tests/test_report.py
- sell/tests/test_finance.py
> [FIX] money/bank_statements 提高覆盖率 完善

- web_export_view_good/tests/test_web_export_view.py
> web_export_view_good test添加。。

- common_dialog/model.py
- common_dialog/wizard/wizard.py
- sell/sell.py
- sell/tests/__init__.py
- sell/tests/test_common_dialog.py
- sell/tests/test_sell.py
> [ADD]增加sell测试，goods_inventory()的覆盖，common_dialog模块中弹窗确认按钮的覆盖

- buy/wizard/buy_payment_wizard.py
- sell/wizard/sell_receipt_wizard.py
> [FIX]buy_payment_wizard.py 付款率计算修改，单据金额不可能为0,sell计算收款率做同样修改

- finance/tests/test_report.py
- finance/trial_balance.py
> [ADD] 添加 fiance/trial_balance 测试数据提高覆盖率

- warehouse/tests/test_inventory.py
> [ADD]inventory.py提高覆盖率

- README.md
- gooderp_statistics/static/src/js/main.js
> [IMP]修改readme增加下载链接

- warehouse/production.py
- warehouse/static/src/js/warehouse_widget.js
- warehouse/tests/test_production.py
> 1.test覆盖率提高，2.部分代码顺序调整使其规范。。

- finance/balance_sheet.xml
- finance/trial_balance.py
- finance/trial_balance.xml
> [add]科目明细账增加无发生额、无余额不显示，总账增加无余额不显示，增加科目明细、总账搜索视图。

- buy/buy.py
- core/core.py
- core/tests/test_core.py
- finance/__init__.py
- finance/__openerp__.py
- finance/report_auxiliary_accounting.py
- finance/report_auxiliary_accounting.xml
- finance/security/ir.model.access.csv
- finance/tests/finance_demo.xml
- partner_address/partner_address.xml
- sell/tests/test_finance.py
> 增加辅助核算项明细表 和 辅助核算项余额表 #750

- money/generate_accounting.py
- report_docx/report/report_docx.py
> 打印销货单出错 #753 [尝试解决，本机没有重现]

- buy/buy.py
- money/money_order.py
- money/partner.py
- sell/sell.py
> 不要生成金额为0的invoice #761

- asset/asset.py
- asset/tests/test_asset.py
- buy/buy.py
- finance/finance.py
- finance/finance_view.xml
- money/money_order.py
- money/partner.py
- sell/sell.py
> 十月购进固定资产，从十一月开始折旧，生成固定资产折旧明细显示十月。 #661

- finance/tests/test_report.py
- money/generate_accounting.py
- money/money_order.py
- money/money_transfer_order.py
- money/other_money_order.py
- money/tests/test_reconcile_order.py
- partner_address/partner_address.py
> [ADD] 根据 code review 修改 money_order.py 的代码，并修改相应的测试代码

- core/__init__.py
- core/models/clean_data.py
- core/models/res_company.py
- core/views/core_view.xml
- finance/balance_sheet.py
- finance/balance_sheet.xml
- finance/finance.py
- finance/issue_cost_wizard.py
- warehouse/goods.py
- warehouse/warehouse_move.py
- warehouse/warehouse_move_line.py
- warehouse/warehouse_order.py
>  	发出成本结转支持先进先出法 #771

- sell/report/sell_order_detail.py
- warehouse/view/warehouse_view.xml
- warehouse/warehouse_move.py
- warehouse/warehouse_order.py
> 去掉调拨单上的业务伙伴字段 #778

- task/__manifest__.py
- task/models/task.py
- task/security/ir.model.access.csv
- task/views/views.xml
> [ADD]add access and add task kan 

- core/views/core_view.xml
- money/home_page_data.xml
> 有查看消息的组，才能够看到讨论菜单 #789

- finance/wizard/checkout_wizard.py
> [IMP]finance结账支持损益类科目有相反方向发生额

- asset/asset.py
- core/models/res_company.py
- core/static/src/xml/base.xml
- staff/staff.py
- staff/tests/staff_demo.xml
- staff/tests/test_staff.py
- web_export_view_good/tests/test_web_export_view.py
> 解决一下这些 warning #786

- task/__manifest__.py
- task/data/data.xml
- task/demo/demo.xml
- task/models/task.py
- task/tests/__init__.py
- task/tests/test_task.py
- task/views/views.xml
> [ADD]增加任务指派方法，增加今日、报表、设置菜单

- task/demo/demo.xml
- task/models/task.py
- task/tests/test_task.py
- task/views/views.xml
> [ADD]task模块增加name_get()和create方法的测试

- warehouse/inventory.py
> [FIX]盘盈盘亏数量改为计算字段，绕过readonly字段不保存的问题

- core/static/src/js/core.js
- web_error_dialog/static/src/js/dialog.js
> 把设置默认值的菜单（选项）移到更多里面。

- core/security/groups.xml
- task/__manifest__.py
- task/security/groups.xml
- task/views/views.xml
> [ADD]增加任务经理组和管理时间组，只有经理组的用户才能看到报表和设置菜单

- finance/finance.py
- task/__manifest__.py
- task/data/data.xml
- task/demo/demo.xml
- task/models/task.py
- task/security/groups.xml
- task/security/ir.model.access.csv
- task/tests/test_task.py
- task/views/views.xml
> [ADD]project上增加产生发票功能 及 测试

- sell/models/sell_delivery.py
> [FIX]修改审核发货单的bug：当库存不足时弹不出补货向导

- buy/models/buy_receipt.py
- money/money_order.py
- sell/models/sell_delivery.py
> [FIX]审核发货单时报错，发货单的销售费用生成结算单时partner 错取成发货单的partner了

- task/data/data.xml
- task/demo/demo.xml
- task/models/task.py
- task/tests/test_task.py
> [FIX]project上去掉客户必输，不输入客户时不生成结算单	[ADD]task模块project.invoice增加税率的判断及测试

- staff/staff.py
- staff/staff.xml
- staff/tests/staff_demo.xml
- staff/tests/test_staff.py
> [FIX] staff: 添加测试数据，员工合同到期，发送邮件给相关人员

- partner_address/partner_address.py
---
修改采购时供货商的地址字段显示False的问题，刚提交的只是修改销售时客户地址字段的显示问题
提交前:
---
采购时供货商的地址默认没有填时，改字段显示False
提交后:
---
不显示 Fasle
--
修改采购时供货商的地址字段显示False的问题，刚提交的只是修改销售时客户地址字段的显示问题
> 修改采购时供货商的地址字段显示False的问题

- buy/models/buy_order.py
- buy/models/buy_receipt.py
- buy/tests/test_buy_order.py
- buy/tests/test_buy_receipt.py
- buy/views/buy_receipt_view.xml
- money/money_order.py
- partner_address/partner_address.py
- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/tests/test_sell_delivery.py
- sell/tests/test_sell_order.py
- sell/views/sell_view.xml
- task/views/views.xml
> [FIX]采购和销售费用类别在界面上加过滤。业务伙伴地址显示的bug,compute方法少加了依赖

- finance/issue_cost_wizard.py
> [FIX]发出成本计算保留2位小数避免汇总出现差异导致借贷不平

- core/security/groups.xml
- core/views/core_templates.xml
- core/views/core_view.xml
> 隐藏 应用 菜单下的两个菜单 #823

- warehouse/production.py
---
提交前:
---
提交后:
---生成凭证
借：组装产品对应分类的科目 组合件金额
贷：公司的主营业务成本(finance.account_cost)科目 部件金额
贷：公司上的生产费用科目 组装\拆卸金额
--
> 组装单拆卸单生成会计凭证 #820

- finance/company.xml
- finance/finance.py
- finance/finance_view.xml
- warehouse/production.py
> 	组装单拆卸单生成会计凭证 #820[bug fix] 科目寫的不對

- finance/data/finance_data.xml
- finance/finance.py
> [FIX]在同一个模块的py里引用了xml的数据造成ci fail

- buy/models/buy_order.py
- buy/models/money.py
- buy/views/buy_order_view.xml
- sell/models/money.py
- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/views/sell_view.xml
> [FIX]修改销货订单收款状态，原来写法忽略了通过核销单来核销发货单的情况；购货订单做相同修改。

- scm/__openerp__.py
- scm/data/stock_request_data.xml
- scm/stock_request.py
- scm/tests/__init__.py
- scm/tests/test_scm.py
> [UPD] 按需补货 #816 添加部分测试数据并修改相应代码

- scm/stock_request.py
- scm/view/stock_request_view.xml
> [FIX] 组合产品审核不用输入供应商

- warehouse/report/stock_balance.py
> [FIX]库存余额表bug:成本没有随数量更新

- scm/stock_request.py
- scm/tests/test_scm.py
> [UPD] 按需补货 #816 完善测试数据，调整代码

- warehouse/view/warehouse_view.xml
- warehouse/warehouse_move.py
---
提交前:
--- 移库单的源仓库和目的仓库无法通过函数复写来改变
提交后:
---移库单的源仓库和目的仓库 可以 通过函数复写来改变
--
> [IMP] 优化代码，用于 移库单 的源仓库和目的仓库的默认值设置 and 调拨单里面，增加扫描条形码功能

- warehouse/warehouse_move.py
> [IMP] 扫条形码的时候，加入条形码检测函数，用于定制更细化的判定算法

- core/data/core_demo.xml
- core/views/core_view.xml
- sell/__openerp__.py
- sell/tests/test_report.py
- staff/staff.py
- staff/tests/staff_demo.xml
- staff/tests/test_staff.py
> [FIX]将demo数据staff lili从core移到staff模块，增加sell对staff的依赖

- goods/goods_demo.xml
---
提交前:
---
提交后:
---
--
工程如果有需求定制CODE的唯一性的话，测试用例的数量不会冲突
> [FIX] GOODS DEMO DATA中的code保持唯一

- task/views/views.xml
> [FIX] #845 任务中不新建项目

- finance/finance.py
- staff/staff.py
- staff/staff.xml
- task/views/views.xml
> [FIX]员工、员工部门、项目创建时将type传入context，以便生成辅助核算时type各自对应

- buy/data/buy_demo.xml
- buy/models/buy_receipt.py
- core/models/clean_data.py
- core/models/core.py
- core/models/res_company.py
- core/models/res_users.py
- core/tests/test_core.py
- finance/balance_sheet.py
- finance/finance.py
- finance/trial_balance.py
- money/wizard/bank_statements_wizard.py
- money/wizard/other_money_statements_wizard.py
- money/wizard/partner_statements_wizard.py
- scm/stock_request.py
- sell/models/sell_order.py
- staff/tests/test_staff.py
- warehouse/res_company.py
- warehouse/tests/test_goods.py
- warehouse/tests/test_production.py
> 	[ADD] 提升 scm 模块测试覆盖率; [IMP] 优化 money,core,finance 模块字段 default 赋值，以便继承

- task/views/views.xml
> [ADD] 任务增加日历视图 #854

- core/views/core_view.xml
- finance/finance.py
- finance/tests/test_finance.py
- finance/tests/test_report.py
- scm/stock_request.py
- sell/tests/test_ReportDocx.py
> [ADD] 添加 report_docx/report/report_helper.py 测试数据，提高覆盖率

- asset/tests/test_asset.py
- finance/tests/test_finance.py
- warehouse/tests/test_warehouse.py
- warehouse/tests/test_warehouse_order.py
> 	[ADD] 添加  asset/asset.py, finance/ finance.py, finance/checkout_wizard.py 测试数据

- gooderp_statistics/__openerp__.py
> [IMP]auto_install

- buy/data/home_page_data.xml
- core/static/src/js/core.js
- money/home_page_data.xml
- sell/data/home_page_data.xml
- task/__manifest__.py
- task/data/home_page.xml
- warehouse/data/home_page_data.xml
> 	首页内容调整 #862	二级菜单鼠标悬停即展开 #861

- finance/tests/test_report.py
- sell/tests/test_ReportDocx.py
> 	[UPD] 添加 ir_report ,  balance_sheet 测试数据

- core/models/res_users.py
- core/views/core_view.xml
- scm/stock_request.py
- sell/models/sell_order.py
- staff/tests/test_staff.py
- warehouse/warehouse_move.py
> [FIX]员工上绑定对应用户，原来做法错误。staff_id 默认值重新赋值

- finance/tests/test_exchange.py
- money/report/bank_statements.py
- warehouse/tests/test_production.py
> 	[FIX] 现金银行报表 资金转账单，考虑 外币币别

- goods/action/goods_action.xml
- goods/menu/goods_menu.xml
- goods/view/goods_view.xml
> [IMP]增加属性值菜单，便于删除没用的属性值

- finance/finance.py
- goods/goods.py
- goods/view/goods_view.xml
- money/money_order.py
- warehouse/warehouse_move_line.py
> 【商品】中增加“备注”栏位 #876

- finance/finance.py
- finance/trial_balance.py
- money/partner.py
- warehouse/goods.py
> 产品的收入和成本科目应有默认值 #878

- buy/models/buy_receipt.py
- buy/views/buy_receipt_view.xml
- goods/view/goods_view.xml
- money/generate_accounting.py
- money/money_order.py
- sell/models/sell_delivery.py
- sell/views/sell_view.xml
> [ADD] 采购销售费用行增加税额字段，带到发票上 #881

- sell/models/sell_delivery.py
> [FIX]销售发货单生成money_order的时候没有考虑 partner_cost #885

- core/models/goods.py
---
提交前:
---
产品转化率只给了默认值0，改成0可以保存
提交后:
---
改成0 不 可以保存
--
> [IMP] 增加产品软化率合法性判定，不能为0

- core/static/src/js/core.js
- core/static/src/xml/base.xml
- fixed_header/__init__.py
- fixed_header/__openerp__.py
- fixed_header/fixed_header.xml
- fixed_header/static/src/js/fixed_header.js
- fixed_header/static/src/lib/sticky_table_header/jquery.floatThead.js
> tree页面固定表头(自己开发的模块.)可能有部分的bug

- finance/finance.py
- fixed_header/static/src/js/fixed_header.js
> 1.会计凭证复制时不应该复制凭证号.2.tree 页面 表头固定 影响到form中的tree[bug fix]

- finance/finance.py
- finance/trial_balance.py
> 会计凭证复制时凭证行copy =True date copy=False

- finance/balance_sheet.py
- finance/trial_balance.py
> 科目总账明细帐 期间显示异常调整.[bug fix]

- money/money_order.py
- money/money_transfer_order.py
- money/tests/test_reconcile_order.py
> [ADD] 代码里面一些数字比较没有存在小数精度的问题。 #886

- goods/view/goods_view.xml
> [IMP]全尺寸商品图片

- goods/view/goods_view.xml
> [IMP]图片显示为300*300

- finance/wizard/checkout_wizard.py
> [FIX]年度结转未分配利润应考虑全年本年利润

- warehouse/inventory.py
> [IMP] #907 盘点单中的仓库，给出默认值，支持继承修改

- warehouse/data/warehouse_demo.xml
- warehouse/tests/test_warehouse.py
- warehouse/view/inventory_view.xml
- warehouse/warehouse_move.py
> [ADD]盘点单 支持扫码改变盘点数量 #895

- warehouse/data/warehouse_demo.xml
- warehouse/warehouse_move.py
---
提交前:
---
当盘点两个产品时，扫码输入一个产品，结果两个产品的数量和辅助数量都改变
提交后:
---
当盘点两个产品时，扫码输入一个产品，只改变对应产品的数量和辅助数量
--
> [FIX]盘点单 支持扫码改变盘点数量 #895 修改bug：当盘点两个产品时，扫码输入一个产品，结果两个产品的数量和辅助数量都改变

- core/views/core_view.xml
- sell/views/sell_view.xml
> [ADD] 允许将客户转为供应商 #926

- core/models/res_company.py
- goods/goods.py
- staff/staff.py
- staff/staff.xml
- staff/tests/test_staff.py
> 员工菜单使用看板视图 #911

- buy/tests/test_buy_adjust.py
- buy/tests/test_buy_receipt.py
- sell/tests/test_sell_adjust.py
- sell/tests/test_sell_delivery.py
> 	[FIX] 完善 税率应跟着商品与供应商/客户走 #865 相关测试数据。提高覆盖率

- warehouse/menu/warehouse_menu.xml
> [ADD] 仓库-调拨单 #929

- money/generate_accounting.py
- money/money_order.py
- money/tests/test_money.py
> [ADD] 收款单/付款单的本次收/付款大于或小于本次核销金额，即为预收/预付  #922

- buy/report/supplier_statements.py
> [IMP] 修改注释

- staff/staff.xml
> 员工看板视图,不能create,造成不方便/

- warehouse/action/warehouse_action.xml
- warehouse/data/sequence.xml
- warehouse/menu/warehouse_menu.xml
- warehouse/production.py
- warehouse/view/production_view.xml
- warehouse/warehouse_move_line.py
> [ADD] 委外加工单 outsource #924 需要添加测试数据

- core/__manifest__.py
- core/models/core.py
- core/views/core_view.xml
- money/view/money_order_view.xml
- task/views/views.xml
- warehouse/action/warehouse_action.xml
- warehouse/menu/warehouse_menu.xml
- warehouse/production.py
- warehouse/security/ir.model.access.csv
- warehouse/view/production_view.xml
- warehouse/wizard/save_bom.py
- warehouse/wizard/save_bom_view.xml
> [FIX] 委外加工单添加 权限

- core/security/groups.xml
- warehouse/menu/warehouse_menu.xml
> 仓库 - 匹配记录 菜单放入no_one组 #946

- warehouse/data/warehouse_demo.xml
- warehouse/production.py
- warehouse/tests/test_production.py
> [ADD] 添加 委外加工单的 demo 及测试数据；完善 组装拆卸单 的测试数据

- backend_theme/static/src/less/form_adaption.less
- core/models/goods.py
- warehouse/production.py
- warehouse/warehouse_order.py
> less考虑不全面引起，部分form视图中的ｔｒｅｅ列表视图定位不准

- buy/models/buy_order.py
- money/money_order.py
> [IMP] 采购单中，确认付款计划时，生成付款单时，银行信息传递过来

- account_cost/__openerp__.py
- account_cost/data/cost_order_demo.xml
- account_cost/models/cost_order.py
- account_cost/tests/__init__.py
- account_cost/tests/test_cost_order.py
- buy/report/supplier_statements.py
- money/money_order.py
- money/other_money_order.py
- money/tests/test_money.py
- staff/staff.xml
- warehouse/inventory.py
- warehouse/production.py
- warehouse/tests/test_inventory.py
- warehouse/tests/test_move_line.py
- warehouse/view/inventory_view.xml
- warehouse/warehouse_move.py
- warehouse/warehouse_move_line.py
> 	[ADD] 添加 account_cost 测试数据;	 [UPD] 添加 money_transfer_order 测试数据

- buy/models/buy_order.py
> [IMP]采购单生成采购入库单时，到期日期默认为订单的交期

- task/security/groups.xml
- task/views/views.xml
> [FIX]使任务form视图上任务阶段可点击，修改管理任务组的继承

- buy/models/buy_receipt.py
- buy/report/supplier_statements.py
- money/money_order.py
- money/money_transfer_order.py
- sell/models/sell_delivery.py
- sell/report/customer_statements.py
> [FIX] 收付款有 discount_amount 时，收付款单审核、反审核修改；代码优化

- money/money_order.py
- scm/stock_request.py
- warehouse/data/warehouse_demo.xml
- warehouse/production.py
> [FIX] 补货申请 内部移库时，当前库存计算修正

- money/money_order.py
- money/view/money_order_view.xml
> [FIX] #975 收付款单，结算单编号。且核销单中显示到期/付款单中，搜索核销单的算法独立成一函数，方便定制

- money/money_order.py
- money/view/money_order_view.xml
> [IMP] 结算单中加入放大镜，用来查看原单的信息

- money/view/money_order_view.xml
> [IMP] 结算单中的 单据时间、到期日分组，改为按月分组。比较符合常理

- core/static/src/xml/base.xml
- sell/views/sell_view.xml
- task/models/task.py
> 发货单上的 整单折扣率 去掉，整单折扣额改为 抹零 #979

- buy/views/buy_receipt_view.xml
- sell/views/sell_view.xml
- warehouse/tests/test_move_line.py
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
- warehouse/warehouse_move_line.py
> [FIX] 修复出库明细行上的 lot 不能带到 库存调拨行上的问题

- task/models/task.py
- task/tests/test_task.py
- task/views/views.xml
> [FIX]#983：报表工作日志去掉指派给，在今日工作日志中创建工作记录时如果选择了指派人，则将其更新到对应任务中

- buy/views/buy_receipt_view.xml
- core/models/core.py
- goods/goods.py
- goods/view/goods_view.xml
- sell/views/sell_view.xml
- warehouse/tests/test_move_line.py
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
- warehouse/warehouse_move_line.py
> [IMP]创建属性值界面应该自动将属性填充上，在收支项界面创建其他收入类时应自动填充上类型 #971

- warehouse/warehouse_move.py
> 扫码代码重构,有部分情况少考虑

- warehouse/tests/test_move_line.py
- warehouse/warehouse_move_line.py
> [ADD] Bug，入库单，通过明细行“添加项目”操作，输入商品，没有带出单价填充到“入库单价”列（扫描输入可以） #958

- goods/tests/test_goods.py
- scm/stock_request.py
- scm/tests/test_scm.py
- task/models/task.py
- warehouse/warehouse_move_line.py
> [IMP]优化任务阶段默认值方法，以便继承

- warehouse/warehouse_move_line.py
其他入库单上，入库单元成本单价的计算，根据产品的成本和税率计算去税点后的单价
---
提交前:
---
提交后:
---
--
> [FIX]其他入库单上，入库单元成本单价的计算，根据产品的成本和税率计算去税点后的单价

- money/money_order.py
> [FIX]结算单查看原始单据完善

- core/models/goods.py
- goods/view/goods_view.xml
- sell/models/sell_adjust.py
- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/views/sell_view.xml
- staff/tests/test_staff.py
- warehouse/tests/test_inventory.py
> [ADD] 商品上增加 不可销售 boolean字段 #992 需添加测试数据

- warehouse/warehouse_move.py
> [IMP] 修正扫码录入产品时，wh_move_line的算法

- money/generate_accounting.py
- warehouse/tests/test_warehouse_order.py
- warehouse/warehouse_order.py
> [FIX] Bug，入库单，通过明细行“添加项目”操作，输入商品，没有带出单价填充到“入库单价”列（扫描输入可以） #958 需要查看 ci

- money/money_order.py
- scm/tests/__init__.py
- scm/tests/test_money_invoice.py
---
增加测试覆盖率
提交前:
---
提交后:
---
--
> [IMP]为【在结算单上查找原始单据】增加测试。

- finance/report/report_voucher.xml
- money/money_order.py
- staff/leave.py
- staff/leave.xml
- staff/security/groups.xml
- staff/tests/test_staff.py
> [ADD]请假时长修改为手动输入，添加人事经理组。

- finance/finance.py
- finance/tests/test_finance.py
- finance/tests/test_report.py
> [ADD] 期间的名称简化为 年+月，如201605 #1007

- buy/models/buy_adjust.py
- buy/models/buy_order.py
- sell/models/sell_adjust.py
- sell/models/sell_order.py
- sell/views/sell_view.xml
- warehouse/warehouse_move_line.py
> [IMP]使用inverse参数实现含税价和不含税价的互算 #1004

- money/generate_accounting.py
> [ADD] 资金-其他收入单/其他支出单选择多个类别或者收支项，贷方生成一条凭证行 #1010

- warehouse/report/stock_balance_view.xml
- web_error_dialog/static/src/js/dialog.js
> [IMP]库存余额表不需要根据单位搜索，报错窗口定位到用户社区

- buy/tests/test_buy_receipt.py
- money/generate_accounting.py
- money/tests/test_money.py
> 	[FIX] 添加 buy_receipt 采购入库审核 和  generate_accounting 其他收支单生成凭证 测试数据

- sell/views/sell_view.xml
> [IMP]销售模块的商品菜单过滤掉不可销售的产品

- buy/models/buy_order.py
- buy/tests/__init__.py
- sell/models/sell_order.py
- task/demo/demo.xml
- warehouse/data/sequence.xml
- warehouse/data/warehouse_demo.xml
- warehouse/inventory.py
- warehouse/production.py
- warehouse/tests/test_warehouse_order.py
- warehouse/view/production_view.xml
- warehouse/warehouse_move.py
---
移库单审核后明细行类型
提交前:
---
移库单审核后明细行类型是出库
提交后:
---
移库单审核后明细行类型是内部调拨
--
> [FIX]移库单对应的move_line行类型应该是internal #1015

- money/generate_accounting.py
> 付款单生成会计凭证未考虑外币 #1021

- warehouse/production.py
- warehouse/view/production_view.xml
> [FIX]修复组装单、拆卸单、委外加工单在保存时不显示出库明细行的bug：通过修改onchange方法

- buy/models/buy_order.py
- buy/views/buy_order_view.xml
- buy/views/buy_receipt_view.xml
- money/generate_accounting.py
- money/tests/test_money.py
- sell/models/sell_order.py
- sell/views/sell_view.xml
> 收款单生成会计凭证未考虑外币 #1021（付款单不用外币支付）

- warehouse/production.py
- warehouse/tests/test_production.py
- warehouse/view/production_view.xml
- warehouse/warehouse_move.py
> 	[ADD] 组装单、拆卸单、委外加工单审批两步，第一步投料，第二步产出成品 #1029 已完成委外加工单的流程，接下来完成组装拆卸单（类似）

- warehouse/move_matching.py
- warehouse/production.py
- warehouse/tests/test_production.py
- warehouse/view/production_view.xml
- warehouse/warehouse_move.py
> 	[ADD] 组装单、拆卸单、委外加工单审批两步，第一步投料，第二步产出成品 #1029 需要添加测试数据

- buy/models/buy_adjust.py
- buy/report/buy_order_track_view.xml
- buy/wizard/buy_order_track_wizard.py
- sell/models/sell_adjust.py
- sell/models/sell_order.py
- sell/report/sell_order_track_view.xml
- sell/wizard/sell_order_track_wizard.py
> [IMP]审核变更单时应将变更单号写到原单据行备注中

- buy/report/buy_payment_view.xml
- buy/wizard/buy_payment_wizard.py
- sell/report/sell_receipt_view.xml
- sell/wizard/sell_receipt_wizard.py
> [IMP]采购付款/销售收款一览表使用avg= #1058

- buy/models/buy_adjust.py
- buy/models/buy_order.py
- sell/models/sell_adjust.py
- sell/models/sell_order.py
- task/models/task.py
- task/tests/test_task.py
- warehouse/warehouse_move_line.py
> [IMP]任务模块：主数据-项目里，未选择客户，在发票行点击生成发票需要报错 #1061

- finance/trial_balance.py
- money/generate_accounting.xml
- money/money_order.py
- money/report/other_money_statements.py
- money/report/other_money_statements_view.xml
- money/view/money_order_view.xml
- sell/models/sell_delivery.py
- warehouse/action/warehouse_action.xml
- warehouse/data/warehouse_data.xml
- warehouse/res_company.py
- warehouse/tests/test_warehouse_order.py
- warehouse/view/res_company.xml
- warehouse/warehouse_order.py
> 	其他入库单 和 其它出库单 菜单点击后界面title没有“其他”字样，容易误解 #1044其他入库单 和 其它出库单 菜单点击后界面tit

- buy/report/supplier_statements.py
- money/tests/test_invoice.py
- sell/report/customer_statements.py
- staff/__openerp__.py
- staff/security/groups.xml
- staff/security/rules.xml
- warehouse/warehouse_order.py
> [ADD] 添加 staff.leave 的权限：员工可以查看所有人的请假记录，但不能创建、修改或删除其他人的请假记录

- buy/views/buy_receipt_view.xml
- money/money_order.py
- scm/__openerp__.py
- scm/tests/test_money_invoice.py
- sell/views/sell_view.xml
> [FIX]增加scm模块对task的依赖，以解决装scm模块时test 报错

- core/models/goods.py
> [IMP] 产品不可销售属性，改成可以定制此值

- core/static/src/js/core.js
> 实现在form页面上的 one2many字段 子字段的必输报错的详细提示.

- finance/finance_conf.xml
- staff/leave.py
- staff/leave.xml
- staff/staff.xml
- staff/tests/test_staff.py
> [FIX]人力资源模块界面调整 #1068

- finance/voucher_template.py
- finance/voucher_template.xml
> [ADD]会计：凭证模板放在设置菜单下并增加辅助核算列 #1072

- core/models/goods.py
> [IMP] 产品名称复制的时候加“副本”，前面加判定条件，以扩展

- sell/models/sell_adjust.py
- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/views/sell_view.xml
> [FIX]避免不可销售的产品无法添加到组装单

- finance/data/finance_data.xml
- finance/finance.py
- finance/finance_view.xml
- finance/report_auxiliary_accounting.py
- finance/report_auxiliary_accounting.xml
- finance/security/ir.model.access.csv
- finance/tests/test_exchange.py
- finance/tests/test_finance.py
- finance/trial_balance.py
- finance/trial_balance.xml
- finance/wizard/checkout_wizard.py
- finance/wizard/checkout_wizard.xml
> [FIX] 会计模块finance.py待修复的一些小问题 #1081 代码及测试完善

- core/models/goods.py
---
提交前:
---
many2one字段搜索时，出现domain之外的产品
提交后:
---
--
> [IMP] 产品搜索时，code的搜索时在domain的条件下叠加。

- core/security/groups.xml
- good_crm/__manifest__.py
- good_crm/security/groups.xml
- good_crm/views/crm_view.xml
- task/__manifest__.py
- task/models/task.py
- task/security/ir.model.access.csv
- task/security/rules.xml
- task/tests/test_task.py
- task/views/views.xml
> [FIX]task模块增强 #1096：允许项目经理和客户查看项目的计划工时和实际工时的差异，增加备注及继承消息等

- account_cost/__openerp__.py
- asset/__openerp__.py
- buy/__openerp__.py
- finance/__openerp__.py
- finance/tests/finance_demo.xml
- good_crm/__manifest__.py
- goods/__openerp__.py
- money/__openerp__.py
- scm/__openerp__.py
- sell/__openerp__.py
- staff/__openerp__.py
- task/__manifest__.py
- warehouse/__openerp__.py
> 	gooderp模块间的依赖调整简化。	新建数据库，勾选演示数据，会计凭证示例和配置类别有错误 #1094

- task/security/rules.xml
> [FIX]修改 门户用户进入项目菜单后弹出没有res_partner的read权限 的问题

- goods/__openerp__.py
- goods/goods.py
- goods/view/goods_view.xml
> [IMP]GOODS模块代码优化：属性及属性值类的定义加上description，方法中变量名修改，及字段修改，goods属性界面显示修改

- core/models/pricing.py
> [IMP]core模块完善 #1105: 简化pricing.py

- money/money_order.py
> [FIX]修复bug:收付款单反审核时未核销金额错误 #1113

- money/models/generate_accounting.py
- money/models/money_order.py
- money/models/money_transfer_order.py
- money/models/other_money_order.py
- money/models/partner.py
- money/views/money_order_view.xml
- money/views/money_transfer_order_view.xml
- money/views/other_money_order_view.xml
…py和xml文件2.Money models generate_accounting.py文件里需要修改的地方 #1126
---
提交前:
---
提交后:
---
--
> [IMP]1.补充修改money/models下py文件2.Money models generate_accounting.py文件里需要修改的地方 #1126

- asset/models/asset.py
- asset/tests/test_asset.py
> [FIX]初始化固定资产，未审核状态下在期初会计凭证下引入固定资产时不应生成凭证，应审核后生成。 #1125

- asset/tests/test_asset.py
- money/models/generate_accounting.py
- money/report/bank_statements.py
- money/report/bank_statements_view.xml
- money/views/generate_accounting.xml
- money/views/money_order_view.xml
- money/views/other_money_order_view.xml
- money/views/partner_view.xml
> [FIX]解决generate_accounting.py的冲突[IMP]generate_accounting.xml/bank_statements.py需要修改的地方 #1134

- money/wizard/other_money_statements_wizard.py
- money/wizard/partner_statements_wizard.py
> [IMP]Money wizard parther_statements_wizard.py里需要修改的地方 #1128

- buy/report/supplier_statements.py
- money/report/bank_statements.py
- sell/report/customer_statements.py
> [FIX]修复供应商/客户对账单不能查看核销单的原始单据的bug:#1118

- asset/models/asset.py
- asset/tests/test_asset.py
- finance/models/finance.py
> [FIX]在引入固定资产初始化单时，如果系统中存在未审核的固定资产初始化单，则应给用户提醒信息而非忽略。#1125

- money/models/money_order.py
> 在many2one字段里有order则显示单号，否则显示名称_票号

- backend_theme/static/src/less/left_button.css
---
backend_theme 手机屏幕时不能隐藏左侧按钮
提交前:
---
backend_theme 手机屏幕时不能隐藏左侧按钮
提交后:
---
backend_theme 手机屏幕时可以隐藏左侧按钮
--
> backend_theme 手机屏幕时隐藏左侧按钮

- partner_address/models/partner_address.py
- partner_address/views/partner_address.xml
> [IMP] 客户联系人增加邮箱

- staff/models/staff_contract.py
- staff/views/staff.xml
> 因为养老，失业，医疗，住房不一定于工资成一定比例，故增加字段填写，人事经理可看

- buy/models/buy_order.py
- buy/models/buy_receipt.py
- sell/views/sell_view.xml
> 生成付款时带出银行信息，修改错别字

- home_page/models/home_page.py
> _description  等 在py 中加中文的地方一定要记得加u 不然会在某些遇到报错..

- goods/models/goods.py
- goods/tests/test_goods.py
- home_page/models/home_page.py
- sell/models/sell_delivery.py
- warehouse/models/goods.py
- warehouse/models/warehouse_move.py
- warehouse/models/warehouse_move_line.py
- warehouse/models/warehouse_order.py
- warehouse/tests/test_warehouse_order.py
> [FIX]warehouse goods.py里需要修改的地方 #1150：其他出库单应产生负库存等

- buy/models/buy_receipt.py
- money/models/partner.py
- money/report/other_money_statements.py
- money/report/other_money_statements_view.xml
- sell/models/sell_delivery.py
> [FIX]资金-其他收支明细表，类别和收支项显示的内容不正确；金额应加上税额 #1160

- buy/views/buy_receipt_view.xml
- money/report/bank_statements.py
- money/report/bank_statements_view.xml
- sell/views/sell_view.xml
- warehouse/models/goods.py
- warehouse/models/move_matching.py
- warehouse/models/warehouse_move_line.py
- warehouse/security/groups.xml
- warehouse/tests/test_move_line.py
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
> [ADD]商品保质期管理 #1149；[FIX]修改现金银行报表账户余额全为0的bug

- staff/tests/staff_demo.xml
- staff/tests/test_staff.py
> [ADD]提高staff_leave.py测试覆盖率

- buy/views/buy_receipt_view.xml
- sell/views/sell_view.xml
- warehouse/__openerp__.py
- warehouse/action/warehouse_action.xml
- warehouse/menu/warehouse_menu.xml
- warehouse/models/__init__.py
- warehouse/models/qc_rule.py
- warehouse/models/warehouse_move.py
- warehouse/security/ir.model.access.csv
- warehouse/tests/__init__.py
- warehouse/tests/test_qc_rule.py
- warehouse/view/production_view.xml
- warehouse/view/qc_rule.xml
- warehouse/view/warehouse_view.xml
> [ADD]出入库增加质检环节 #1148

- staff/models/leave.py
- staff/models/staff.py
- staff/models/staff_contract.py
> [FIX]staff 模块：为每个对象增加公司字段

- core/static/src/js/core.js
- core/static/src/less/core.less
- core/static/src/xml/base.xml
- core/views/core_templates.xml
- warehouse/models/qc_rule.py
> [FIX]realize pdf view function for field qc_result. 仓库模块的单据菜单下的子菜单-移库单，希望与其他地方的一致 #1173

- buy/views/buy_receipt_view.xml
- sell/views/sell_view.xml
- warehouse/security/groups.xml
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
> [IMP]增加管理质检组，在该组的人才能看到质检报告字段

- staff_wages/demo/staff_wages_demo.xml
- staff_wages/models/staff_wages.py
- staff_wages/tests/test_staff_wages.py
- staff_wages/views/wages_view.xml
> [ADD]工资模块测试

- web_error_dialog/__openerp__.py
> [FIX]增加web_error_dialog对web的依赖

- buy/models/buy_receipt.py
- sell/models/sell_delivery.py
- task/views/views.xml
> [IMP]任务模块两处修改 #1179

- task/views/views.xml
- warehouse/models/production.py
- warehouse/models/warehouse_move.py
- warehouse/view/production_view.xml
> [FIX]修改质检报告的bug:组装单、拆卸单及委外加工单审核时候没有验证是否上传质检报告

- buy/data/home_page_data.xml
- sell/data/home_page_data.xml
> [FIX]首页点击应付余额，界面不应该显示客户 #1164

- finance/models/issue_cost_wizard.py
- home_page/models/home_page.py
- home_page/static/src/js/home_page.js
- home_page/views/home_page_views.xml
> 	home_page bug fix .

- staff_wages/models/staff_wages.py
- staff_wages/tests/test_staff_wages.py
> [ADD]工资模块的测试文件

- buy/models/buy_order.py
- buy/models/buy_receipt.py
- buy/tests/test_buy_order.py
- buy/views/buy_order_view.xml
- buy/views/buy_receipt_view.xml
- sell/views/sell_view.xml
> [ADD]需要采购支持多货币 #1133

- staff_wages/models/staff_wages.py
- task/views/views.xml
> [FIX]修改任务工作日志报表并不能过滤出今日的bug

- staff_wages/tests/test_staff_wages.py
> [IMP]改进工资模块的测试

- home_page/static/src/js/home_page.js
> home_page bug  fix .

- buy/models/buy_receipt.py
- finance/models/finance.py
- finance/tests/test_finance.py
- money/models/generate_accounting.py
- staff_wages/models/staff_wages.py
> [FIX]修改bug:收银行利息，在资金模块其他收入单输入金额，审核后生成会计凭证，在利润表不显示利息收入 #1174

- staff_wages/views/wages_view.xml
> [ADD]人力资源-员工工资选择付款方式，只可选择，不能新建 #1169

- sell/models/sell_delivery.py
- sell/tests/test_sell_delivery.py
> [ADD]销售模块的测试文件补充

- finance/data/finance_data.xml
- finance/models/finance.py
- finance/models/issue_cost_wizard.py
- finance/tests/finance_demo.xml
- good_crm/__manifest__.py
- good_crm/data/crm_data.xml
- good_crm/models/crm.py
- good_crm/security/groups.xml
- good_crm/security/ir.model.access.csv
- good_crm/views/crm_view.xml
- sell/models/sell_delivery.py
- sell/security/groups.xml
- sell/views/sell_view.xml
- task/models/task.py
- task/views/views.xml
- warehouse/models/production.py
- warehouse/models/warehouse_move.py
- warehouse/models/warehouse_order.py
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
> [ADD]商机界面增加字段 #1197

- finance/models/issue_cost_wizard.py
- sell/models/sell_delivery.py
- warehouse/models/production.py
- warehouse/view/production_view.xml
> [FIX]成本核算逻辑修改 #1207： 4、拆卸单、委外加工单材料出库生成会计凭证，5、月末结转发出成本修改

- core/models/partner.py
- core/tests/test_core.py
> [IMP]partner支持按代码name_search #1205

- backend_theme/static/src/less/left_button.css
- backend_theme/views/web.xml
> 主题关于左边菜单的滚动条的css 设置。

- finance/models/finance.py
- finance/tests/test_finance.py
- money/models/money_order.py
- money/models/other_money_order.py
- money/views/money_order_view.xml
- money/views/other_money_order_view.xml
- report_docx/models/ir_actions.py
- staff/models/staff.py
- staff/views/staff.xml
- warehouse/models/production.py
- warehouse/models/warehouse_move_line.py
> [FIX]#1207：组装单、拆卸单、委外加工单入库凭证的贷方科目由主营业务成本改成核算类别上科目

- finance/models/finance.py
- finance/tests/test_finance.py
- finance/views/finance_view.xml
- money/tests/test_invoice.py
- warehouse/models/production.py
> [FIX]#1207：组装拆卸委外审核时出入库凭证行修改;	[FIX]只在凭证界面明细行上会计科目下拉里显示余额

- finance/tests/test_finance.py
- money/tests/test_money.py
> [ADD]提高finance.py和other_money_order.py覆盖率

- core/static/src/xml/base.xml
- finance/data/finance_data.xml
- finance/tests/finance_demo.xml
- staff/models/staff_contract.py
- staff/tests/staff_demo.xml
- staff/views/staff.xml
- staff_wages/models/staff_wages.py
- staff_wages/tests/test_staff_wages.py
- staff_wages/views/wages_view.xml
> [ADD]工资行上增加公司五险一金后生成计提凭证

- staff_wages/data/wages_data.xml
- staff_wages/models/staff_wages.py
- staff_wages/tests/test_staff_wages.py
> [ADD]审核工资单时生成需要支付公积金和社保的其他支出单

- account_cost/views/cost_order_view.xml
- buy/views/buy_adjust_view.xml
- buy/views/buy_order_view.xml
- buy/views/buy_receipt_view.xml
- finance/views/finance_view.xml
- good_process/models/mail_thread.py
- good_process/views/good_process.xml
- money/models/money_order.py
- money/models/money_transfer_order.py
- money/models/other_money_order.py
- money/views/money_order_view.xml
- money/views/money_transfer_order_view.xml
- money/views/other_money_order_view.xml
- money/views/reconcile_order_view.xml
- scm/views/stock_request_view.xml
- sell/views/sell_view.xml
- staff/models/leave.py
- staff/views/leave.xml
- staff_wages/models/staff_wages.py
- staff_wages/views/wages_view.xml
- warehouse/models/inventory.py
- warehouse/models/production.py
- warehouse/models/warehouse_order.py
- warehouse/view/inventory_view.xml
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
> [IMP]所有单据支持审批流程自定义

- money/views/money_order_view.xml
> [FIX]发票不应填充is_init字段

- buy/models/buy_receipt.py
- finance/models/finance.py
- finance/views/finance_view.xml
- money/models/money_order.py
- sell/models/sell_delivery.py
- warehouse/models/production.py
- warehouse/models/warehouse_order.py
- warehouse/tests/test_production.py
> [FIX]仓库 #1221:2、组装单、拆卸单、委外加工单点击“发料"后不应该能删除；

- good_process/models/mail_thread.py
- good_process/views/good_process.xml
- money/wizard/bank_statements_wizard_view.xml
- money/wizard/other_money_statements_wizard_view.xml
> 审批中不可删除，已审核的单据不可删除，删除时同时删除待审批者

- buy/models/buy_receipt.py
- money/models/generate_accounting.py
- money/views/money_order_view.xml
- money/views/money_transfer_order_view.xml
- money/views/other_money_order_view.xml
- money/views/reconcile_order_view.xml
- sell/models/sell_delivery.py
- staff_wages/__openerp__.py
- staff_wages/models/staff_wages.py
- staff_wages/report/wages_report.xml
- staff_wages/report/wages_templates.xml
- staff_wages/views/wages_view.xml
- warehouse/models/production.py
- warehouse/models/warehouse_order.py
> [ADD]工资行上增加扣款，其他改为补助 #1209

- account_cost/views/cost_order_view.xml
- buy/models/buy_order.py
- buy/models/buy_receipt.py
- buy/views/buy_adjust_view.xml
- buy/views/buy_order_view.xml
- buy/views/buy_receipt_view.xml
- good_process/models/mail_thread.py
- money/views/money_order_view.xml
- money/views/money_transfer_order_view.xml
- money/views/other_money_order_view.xml
- money/views/reconcile_order_view.xml
- scm/views/stock_request_view.xml
- sell/models/sell_delivery.py
- sell/views/sell_view.xml
- staff/views/leave.xml
- staff_wages/views/wages_view.xml
- task/views/views.xml
- warehouse/models/warehouse_order.py
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
> [ADD]所有单据增加审批状态字段

- good_process/models/mail_thread.py
- staff_wages/report/wages_templates.xml
> [IMP]修改工资条模版：表格加上边框

- staff_wages/report/wages_templates.xml
> [FIX]修改工资条打印，表格变细

- core/static/src/js/core.js
- good_process/models/mail_thread.py
- good_process/static/src/js/good_process.js
- good_process/static/src/xml/approver.xml
- warehouse/models/__init__.py
- warehouse/models/scan_barcode.py
- warehouse/models/warehouse_order.py
- warehouse/security/ir.model.access.csv
- warehouse/view/warehouse_view.xml
> 待审批人字体加大，发送的消息的实时页面的更新。

- finance/report/report.py
- finance/report/report_voucher.xml
> [FIX]凭证打印支持负数并调整格式

- buy/models/buy_order.py
- good_process/models/mail_thread.py
- scm/__openerp__.py
- scm/data/demo.xml
- scm/tests/__init__.py
- scm/tests/test_good_process.py
- staff/tests/staff_demo.xml
- staff/tests/test_staff.py
> [ADD]修改审批流程write，增加审批测试

- good_process/models/mail_thread.py
- scm/data/demo.xml
- scm/tests/test_good_process.py
> [ADD]补充审批流程测试

- finance/data/voucher_template.xml
- finance/models/balance_sheet.py
- finance/models/finance.py
- finance/models/trial_balance.py
- finance/views/trial_balance.xml
> 支持建账期初本年累计发生额的录入

- asset/data/asset_data.xml
- asset/views/asset_menu.xml
- finance/data/voucher_template.xml
- finance/views/balance_sheet.xml
- finance/views/exchange.xml
- finance/views/finance_conf.xml
- finance/views/finance_view.xml
- finance/views/issue_cost_wizard.xml
- finance/views/report_auxiliary_accounting.xml
- finance/wizard/checkout_wizard.xml
> [IMP]菜单顺序的调整和隐藏报表模板设置菜单

- finance/models/issue_cost_wizard.py
> [FIX]月末结账，发出成本和实际成本没有差异，不应报错，直接结账 #1252

- warehouse/models/production.py
> [FIX]组装拆卸单据上反审核不应删除出库凭证

- account_cost/models/cost_order.py
- account_cost/views/cost_order_view.xml
- good_process/models/mail_thread.py
- money/models/generate_accounting.py
- money/models/money_order.py
- money/views/money_order_view.xml
- money/views/money_transfer_order_view.xml
- money/views/reconcile_order_view.xml
> [FIX]解决bug:收付款单审批完成后审核报错“已审批不可修改”，反审核方法也做修改

- buy/models/buy_order.py
- buy/views/buy_order_view.xml
- money/models/money_order.py
- scm/models/stock_request.py
- scm/views/stock_request_view.xml
- warehouse/models/production.py
- warehouse/models/warehouse_order.py
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
> [ADD]#1262：采购订单和组装单增加“补货申请”字段，关联到补货申请单

- warehouse/models/warehouse_order.py
> [FIX]提早定义补货申请模型避免升级出错

- buy/models/buy_order.py
- buy/views/buy_order_view.xml
- scm/models/stock_request.py
- warehouse/models/production.py
- warehouse/models/warehouse_order.py
- warehouse/view/production_view.xml
> [FIX]去掉购货订单和组装单与补货申请的关联，组装单上将补货申请号传入备注

- warehouse/models/inventory.py
- warehouse/tests/test_inventory.py
> [FIX]去掉盘点单行辅助数量行检查逻辑

- asset/models/asset.py
- asset/views/asset.xml
- finance/models/finance.py
> [IMP]固定资产界面优化

- sell/models/sell_delivery.py
> [FIX]修复发货单审核时生成出库凭证借贷方不平的bug

- asset/models/asset.py
- asset/views/asset.xml
- finance/models/exchange.py
- finance/models/finance.py
- finance/views/exchange.xml
- finance/views/finance_conf.xml
- finance/wizard/checkout_wizard.py
> [IMP]结账操作向导默认本月最后一天

- staff_wages/models/staff_wages.py
- staff_wages/tests/test_staff_wages.py
> [FIX]BUG：计提工资和生成的其他支出单，应付职工薪酬没有分明细，不能以个人进行辅助核算 #1281

- asset/models/asset.py
- asset/views/asset.xml
- core/models/core.py
- core/models/goods.py
- core/models/partner.py
- core/models/pricing.py
- core/models/warehouse.py
- core/views/core_view.xml
- finance/models/finance.py
- finance/views/finance_conf.xml
- good_process/models/mail_thread.py
- good_process/views/good_process.xml
- goods/view/goods_view.xml
- staff/models/staff.py
- staff/views/staff.xml
- task/models/task.py
- task/views/views.xml
- warehouse/models/production.py
- warehouse/view/production_view.xml
> [IMP]主数据支持归档

- staff/tests/staff_demo.xml
- staff_wages/tests/__init__.py
- staff_wages/tests/test_input_wages.py
> [ADD]增加引入员工工资的测试

- buy/models/buy_order.py
- buy/models/buy_receipt.py
- buy/tests/test_buy_order.py
- buy/tests/test_buy_receipt.py
> [FIX]采购入库单和购货订单允许行中商品的成本为0

- buy/models/buy_adjust.py
- buy/tests/test_buy_adjust.py
> [FIX]采购变更单去掉商品成本不能为0的限制

- finance/models/finance.py
- finance/security/ir.model.access.csv
> [IMP]按期间排序

- finance/models/trial_balance.py
> [FIX]凭证号重排导致的明细账查看凭证按钮报错

- buy/models/buy_adjust.py
- buy/models/buy_order.py
- buy/models/buy_receipt.py
- buy/tests/test_buy_adjust.py
- buy/tests/test_buy_order.py
- sell/models/sell_adjust.py
- sell/models/sell_order.py
- sell/tests/test_sell_adjust.py
- sell/tests/test_sell_delivery.py
- sell/tests/test_sell_order.py
- warehouse/models/warehouse_move_line.py
> [FIX]若不含税价是根据含税价算过来的，不继续反算

- backend_theme/static/src/less/form_adaption.css
- backend_theme/static/src/less/form_adaption.less
- backend_theme/views/web.xml
- home_page/static/src/js/home_page.js
> 左边菜单（开发者模式下带assets）点击后链接拼接不正常, 在web?后面加了一个‘&’号。可能会导致assets模式打开不正确。

- buy/models/buy_receipt.py
- sell/models/sell_delivery.py
- warehouse/models/warehouse_move.py
- warehouse/models/warehouse_order.py
> [FIX]修改发货单、入库单和其他出入库单不能删除多条记录的bug

- finance/models/balance_sheet.py
- finance/models/finance.py
- good_process/models/mail_thread.py
- good_process/static/src/js/good_process.js
- good_process/static/src/xml/approver.xml
- home_page/static/src/js/home_page.js
- ir_sequence_autoreset/__init__.py
- ir_sequence_autoreset/__openerp__.py
- ir_sequence_autoreset/i18n/ir_sequence_autoreset.pot
- ir_sequence_autoreset/i18n/zh_CN.po
- ir_sequence_autoreset/ir_sequence.py
- ir_sequence_autoreset/ir_sequence.xml
> gooderp审批流的小bug的修复。

- asset/data/asset_data.xml
- core/models/core.py
- finance/models/balance_sheet.py
- finance/models/trial_balance.py
- finance/views/trial_balance.xml
> [FIX]库存商品按类别排序问题 #1296

- core/models/res_company.py
- core/views/core_view.xml
- finance/__manifest__.py
- finance/data/finance_voucher_data.xml
- sell/data/home_page_data.xml
> gooderp会计凭证号月末重置设置。（在会计设置中的默认设置只在月末结账中起作用。并不对新创建的凭证的编码产生影响）

- buy/models/buy_receipt.py
- buy/tests/test_buy_order.py
- buy/tests/test_buy_receipt.py
- buy/views/buy_receipt_view.xml
> [ADD]增加buy_order测试覆盖率

- auto_backup/views/bkp_conf_view.xml
- backend_theme/static/src/js/web_responsive.js
- backend_theme/views/web.xml
- core/views/core_view.xml
- partner_address/views/partner_address.xml
- warehouse/models/warehouse_move.py
> 	gooderp根据公司图标变化而改变.

- account_cost/models/cost_order.py
- account_cost/tests/test_cost_order.py
> [ADD]增加account_cost测试覆盖率

- core/views/core_view.xml
- finance/data/finance_data.xml
- finance/models/balance_sheet.py
- warehouse/models/warehouse_order.py
> [FIX]资产负债表模板考虑坏账准备和在产品，修复年初余额计算bug

- money/models/other_money_order.py
> [FIX]修改其他收入单初始化时的init_obj没传入的bug

- core/models/partner.py
- core/views/core_view.xml
- finance/report/report_voucher.xml
> [IMP]凭证打印数字靠下

- buy/views/vendor_goods_view.xml
- good_process/models/mail_thread.py
- warehouse/models/warehouse_order.py
> 添加审批开始的注释 & 供应商的联系人和供应产品使用notebook排列

- buy/models/buy_order.py
- buy/models/money.py
- buy/views/buy_order_view.xml
- good_process/models/mail_thread.py
- good_process/static/src/js/good_process.js
- sell/models/money.py
- sell/models/sell_order.py
- sell/views/sell_view.xml
- warehouse_wave/models/express_menu.py
- warehouse_wave/models/wave.py
- warehouse_wave/static/src/js/lib/jquery.jqprint-0.3.js
- warehouse_wave/static/src/js/warehouse_wave_widget.js
- warehouse_wave/views/assets_backend.xml
- warehouse_wave/views/express_menu.xml
- warehouse_wave/views/wave.xml
> 销售订单、采购订单 收\退款状态 改为 已付款 #1320

- .travis.yml
- scm/tests/test_good_process.py
> [FIX]修复gna.org停服引起的travis-ci失败

- buy/models/buy_receipt.py
- core/security/ir.model.access.csv
- sell/models/sell_delivery.py
> [FIX]发货单生成退货单时，传入折扣额

- core/security/ir.model.access.csv
- warehouse/models/warehouse_move_line.py
> [FIX]把仓库的创建、修改、删除权限给管理仓库组的人

- buy/models/buy_order.py
- buy/models/money.py
- buy/tests/test_buy_order.py
- buy/views/buy_order_view.xml
- sell/models/money.py
- sell/models/sell_order.py
- sell/tests/test_sell_order.py
- sell/views/sell_view.xml
> 销售订单、采购订单 收\退款状态 改为 已付款金额 #1320

- core/views/core_view.xml
- staff/views/staff.xml
- warehouse/models/qc_rule.py
> GoodERP几个小问题 #1318

- staff/views/staff.xml
- warehouse/models/__init__.py
- warehouse/models/location.py
- warehouse/report/stock_balance.py
- warehouse/security/ir.model.access.csv
- warehouse_wave/models/wave.py
- warehouse_wave/security/ir.model.access.csv
> [ADD] 库存余额表，增加按品牌、库位查询，以了解库存余额

- money/models/money_order.py
> [FIX]结算单上，如果逾期金额为0则逾期天数也为0

- buy/models/buy_adjust.py
- buy/models/buy_order.py
- sell/models/sell_adjust.py
- sell/models/sell_order.py
- warehouse/models/warehouse_move_line.py
> [FIX]修复bug:发货单上，修改单价，含税单价和金额并没有跟着修改 #1315

- sell/__openerp__.py
- sell/report/__init__.py
- sell/report/sell_summary.py
- sell/report/sell_summary_view.xml
- sell/security/ir.model.access.csv
> [ADD]销售汇总表:销售用户在任何时候，需要查询销售汇总表（客户、部门、销售员、品牌、产品、销量、销售额）

- buy/models/buy_receipt.py
- sell/models/sell_delivery.py
- warehouse/models/warehouse_move_line.py
> [FIX] 移库单行中的税率改变时，不去重新计算税率

- sell/models/sell_delivery.py
> [FIX] 代码书写错误

- core/models/goods.py
> [FIX]商品的成本改为不必输

- finance/models/finance.py
- finance/tests/test_finance.py
- money/views/partner_view.xml
> [FIX]会计凭证明细上选择了科目后，自动带出外币币别和汇率

- core/models/res_users.py
> [ADD] 创建用户时email字段给个默认值@ #1345

- finance/models/finance.py
- money/models/generate_accounting.py
- money/models/money_order.py
- money/models/partner.py
- money/tests/test_money.py
- money/views/generate_accounting.xml
- money/views/partner_view.xml
> [FIX]账户的外币金额设置为界面只读，可导入但不可在界面修改；收付款单审核和反审核时应该考虑外币

- buy/models/buy_order.py
> [ADD] 采购订单不按收货结算，生成的付款单名字不对 #1348

- good_process/models/mail_thread.py
> [ADD]审批规则加约束：同种单据相同类型必须唯一，未填类型时同种单据必须唯一

- finance/views/finance_view.xml
- top_tree_widget/static/src/js/web_tree_bgcolor.js
- top_tree_widget/static/src/xml/widget.xml
> 修复加了背景色标签，无法显示字段值 的格式的问题，并增加了字体大小的定义。取的是h1~h5。

- gooderp_pos/models/pos_session.py
- gooderp_pos/static/src/css/pos.css
- gooderp_pos/static/src/js/models.js
> [IMP]gooderp_pos 左下角格式调整，重复点击商品增加数量，付款方式取账户

- buy/models/buy_order.py
- buy/models/buy_receipt.py
- sell/models/sell_delivery.py
- sell/models/sell_order.py
> [FIX] 计算购货订单付款/退款状态, 应搜索完成状态的付款单

- warehouse/models/inventory.py
- warehouse/tests/test_inventory.py
- warehouse/view/warehouse_view.xml
> [FIX]盘点单查询的盘点数量不应该包含移库在途的 #1358；库存调拨search视图修改

- money/models/other_money_order.py
- money/models/partner.py
- money/views/other_money_order_view.xml
> [ADD]其他收入单、其他支出单增加外币金额 #1359

- money/report/bank_statements.py
> 现金银行报表增加外币金额字段 #1360

- partner_address/models/partner_address.py
- partner_address/tests/test_partner_address.py
- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/tests/test_sell_delivery.py
- sell/tests/test_sell_order.py
- sell/views/sell_view.xml
- warehouse/models/move_matching.py
- warehouse/models/warehouse_move.py
- warehouse_wave/models/express_menu.py
- warehouse_wave/views/express_menu.xml
- warehouse_wave/views/wave.xml
> [UPD] 库位设置 放到 商品form

- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/tests/test_sell_delivery.py
- sell/views/sell_view.xml
> [ADD]销售发货单重新添加 地址(Char) 字段

- warehouse_wave/models/express_menu.py
> [FIX] 打印快递面单，地址报错

- partner_address/models/partner_address.py
> [FIX] partner 默认地址取第一个联系人的，联系人不存在报错

- money/models/cash_flow_statement.py
- money/views/cash_flow_view.xml
- money/views/generate_accounting.xml
> [IMP]在收支类别上选择现金流量表行，更直观

- sell/models/sell_delivery.py
- warehouse/models/res_company.py
- warehouse/view/res_company.xml
> 增加月末一次性生成成本选项。

- warehouse/models/warehouse_move_line.py
> cost_unit的小数位数应是price

- warehouse_wave/models/wave.py
> [FIX] 打包最后一步，库存不足又允许库存为负时，报错的问题

- buy/views/buy_adjust_view.xml
- buy/views/buy_order_view.xml
- buy/views/buy_receipt_view.xml
- money/views/money_order_view.xml
- money/views/money_transfer_order_view.xml
- money/views/other_money_order_view.xml
- money/views/reconcile_order_view.xml
- sell/views/sell_view.xml
> [ADD] 草稿状态的单据，tree 视图 draft 状态显示为蓝色 #1374

- top_tree_widget/static/src/js/web_tree_bgcolor.js
- top_tree_widget/static/src/js/web_tree_tomany_selected.js
- top_tree_widget/static/src/xml/widget.xml
- top_tree_widget/view/assets.xml
增加在列表上多做选以后的批量删除。
---
提交前:
---
提交后:
---
--
> 优化背景颜色 ，增加对于select类型字段的支持；

- money/models/cash_flow_statement.py
- money/views/cash_flow_view.xml
- money/wizard/cash_flow_wizard.py
> [IMP]现金流量表增加本年累计金额

- buy/models/buy_receipt.py
- buy/views/buy_receipt_view.xml
- finance/data/finance_data.xml
> [ADD]采购入库单上增加收发类别，审核生成入库凭证时贷方科目取收发类别科目，并填充上往来单位

- sell/models/sell_delivery.py
> [ADD] 负库存出货不应该生成金额为0的会计凭证 #1369

- sell/views/sell_view.xml
- warehouse/tests/__init__.py
- warehouse/tests/test_report.py
- warehouse/tests/test_scan_barcode.py
> [ADD]增加onchange_scan_barcode覆盖率

- warehouse_wave/models/express_menu.py
- warehouse_wave/tests/__init__.py
- warehouse_wave/tests/test_express_menu.py
- warehouse_wave/tests/test_wave.py
> [ADD] 添加 生成拣货单，打印拣货单 测试数据

- finance/models/issue_cost_wizard.py
> [ADD]期初建账导入库存的成本，没有被后一个期间月结时计算发出成本取到 #1386

- finance/models/trial_balance.py
> [IMP]科目余额表数值规定小数位数

- finance/models/issue_cost_wizard.py
- sell/tests/test_finance.py
- warehouse_wave/models/express_menu.py
- warehouse_wave/tests/test_express_menu.py
- warehouse_wave/tests/test_wave.py
> [ADD] 添加 打包 测试数据

- sell/models/sell_delivery.py
> [FIX]月第一次生成发出凭证导致的程序报错

- finance/views/finance_view.xml
- money/tests/test_money.py
- money/tests/test_reconcile_order.py
- warehouse_wave/models/report.py
> [ADD] 添加测试数据，提高覆盖率

- warehouse/tests/test_report.py
> [ADD]增加report_base覆盖率

- money/tests/test_report.py
- money/wizard/cash_flow_wizard_view.xml
> [ADD]增加现金流量表测试

- gooderp_pos/data/gooderp_pos_demo.xml
- gooderp_pos/models/pos_config.py
- gooderp_pos/tests/__init__.py
- gooderp_pos/tests/test_pos_config.py
> [ADD]增加pos模块pos_config测试

- core/views/core_view.xml
- task/security/rules.xml
> [UPD] 去掉 门户用户 查看自己项目的权限；供应商 form 显示消息

- core/data/core_demo.xml
- gooderp_pos/models/pos_config.py
- gooderp_pos/models/pos_session.py
- gooderp_pos/tests/test_pos_config.py
- gooderp_pos/views/pos_session_view.xml
- scm/data/demo.xml
- scm/tests/test_good_process.py
> [ADD]增加pos_config pos_session测试，及pos 界面字段翻译

- gooderp_pos/__manifest__.py
- gooderp_pos/models/pos_config.py
- gooderp_pos/models/pos_order.py
- gooderp_pos/models/res_users.py
- gooderp_pos/static/src/js/models.js
- gooderp_pos/tests/test_pos_config.py
- gooderp_pos/views/pos_category_view.xml
- gooderp_pos/views/pos_config_view.xml
- gooderp_pos/views/pos_session_view.xml
> [ADD]pos模块增加pos设置和pos产品分类菜单，会话中付款后生成发货单

- warehouse/models/warehouse_move.py
> [FIX]warehous_move的note不可被复制

- gooderp_pos/__manifest__.py
- gooderp_pos/models/__init__.py
- gooderp_pos/models/goods.py
- gooderp_pos/models/pos_order.py
- gooderp_pos/models/pos_session.py
- gooderp_pos/views/goods_view.xml
- gooderp_pos/views/pos_order_view.xml
- gooderp_pos/views/pos_session_view.xml
- goods/view/goods_view.xml
> [ADD]pos模块增加订单、商品菜单，会话上增加付款明细

- buy/models/buy_order.py
- buy/tests/test_buy_order.py
- gooderp_pos/models/pos_session.py
- gooderp_pos/views/pos_session_view.xml
> [FIX]修改以下bug：购货订单上输入预付款审核后再反审核，账户余额错误

- good_shop/__manifest__.py
- good_shop/controllers/main.py
- good_shop/data/data.xml
- good_shop/models/sell_order.py
- good_shop/static/src/js/good_shop_sale.js
- good_shop/views/good_shop_templates.xml
- good_shop/views/goods_view.xml
> [ADD] good_shop 进一步完善

- asset/models/asset.py
- buy/views/buy_receipt_view.xml
- finance/models/finance.py
- gooderp_pos/models/pos_order.py
- gooderp_pos/models/pos_session.py
- gooderp_pos/static/src/js/models.js
- gooderp_pos/views/pos_session_view.xml
- home_page/models/home_page.py
- money/models/money_order.py
- money/models/money_transfer_order.py
- money/models/other_money_order.py
- scm/models/stock_request.py
- sell/views/sell_view.xml
- staff_wages/models/staff_wages.py
- task/models/task.py
- warehouse/models/inventory.py
- warehouse/models/production.py
- warehouse/models/warehouse_move.py
- warehouse/models/warehouse_move_line.py
- warehouse_wave/models/wave.py
> [ADD]pos会话中进行销售后，在该会话中创建对应的付款明细，付款方式暂时没取到

- good_shop/controllers/main.py
- good_shop/models/sell_order.py
- good_shop/static/src/js/good_shop_sale.js
- good_shop/views/good_shop_templates.xml
- partner_address/models/partner_address.py
> [ADD] shop 完善，客户下单生成销售订单。确认时审核生成出库单。还需要完善 # 1395

- good_shop/controllers/main.py
- good_shop/data/data.xml
- good_shop/models/sell_order.py
- good_shop/static/src/js/good_shop_sale.js
- good_shop/views/good_shop_templates.xml
- money/models/money_order.py
> [ADD] good_shop 允许门户用户选择商品属性，并生成销货订单

- gooderp_pos/models/pos_order.py
- gooderp_pos/models/pos_session.py
- gooderp_pos/static/src/js/models.js
- gooderp_pos/views/pos_session_view.xml
> [FIX]会话上付款明细中按金额汇总

- gooderp_pos/models/pos_order.py
- gooderp_pos/models/pos_session.py
- gooderp_pos/security/ir.model.access.csv
- gooderp_pos/static/src/js/models.js
- gooderp_pos/views/goods_view.xml
- gooderp_pos/views/pos_order_view.xml
- gooderp_pos/views/pos_session_view.xml
> [ADD]增加pos.order，订单结账完生成pos.order

- good_shop/models/sell_order.py
- good_shop/views/good_shop_templates.xml
> [UPD] shop 确认订单，公司账户金额增加

- gooderp_pos/data/gooderp_pos_data.xml
- gooderp_pos/data/gooderp_pos_demo.xml
- gooderp_pos/models/pos_order.py
- gooderp_pos/models/pos_session.py
- gooderp_pos/views/pos_order_view.xml
- gooderp_pos/views/pos_session_view.xml
> [FIX]创建会话时，将pos上的付款方式填充到会话上来；定义会话命名规则及其他

- warehouse_wave/__manifest__.py
- warehouse_wave/data/data.xml
- warehouse_wave/models/express_menu.py
- warehouse_wave/models/wave.py
- warehouse_wave/static/src/js/warehouse_wave_widget.js
- warehouse_wave/static/src/xml/delivery_detail_info.xml
- warehouse_wave/views/wave.xml
> [ADD] #IEQ35 面单上打印格子号，并打印装箱单

- gooderp_pos/__manifest__.py
- gooderp_pos/models/pos_config.py
- gooderp_pos/models/pos_order.py
- gooderp_pos/models/pos_session.py
- gooderp_pos/tests/__init__.py
- gooderp_pos/tests/test_pos_config.py
- gooderp_pos/tests/test_pos_order.py
- gooderp_pos/views/pos_dashboard.xml
- gooderp_pos/views/pos_session_view.xml
- money/security/ir.model.access.csv
> [ADD]新增pos的看板视图 [ADD]增加pos_order.py测试

- buy/views/buy_receipt_view.xml
- core/models/warehouse.py
- money/data/home_page_data.xml
- sell/models/sell_delivery.py
- sell/tests/test_sell_delivery.py
- sell/views/sell_view.xml
- warehouse/__openerp__.py
- warehouse/menu/warehouse_menu.xml
- warehouse/models/__init__.py
- warehouse/models/location.py
- warehouse/models/warehouse_move.py
- warehouse/models/warehouse_move_line.py
- warehouse/security/groups.xml
- warehouse/security/rules.xml
- warehouse/view/warehouse_view.xml
- warehouse_wave/models/wave.py
- warehouse_wave/tests/__init__.py
- warehouse_wave/tests/test_wave.py
- warehouse_wave/views/wave.xml
> [IMP]库位和分拣相关功能的优化

- warehouse_wave/models/express_menu.py
- warehouse_wave/models/wave.py
- warehouse_wave/tests/__init__.py
- warehouse_wave/tests/test_express_menu.py
- warehouse_wave/tests/test_wave.py
> [FIX] 面单打印 添加编码方式

- warehouse_wave/models/wave.py
- warehouse_wave/tests/test_wave.py
> [FIX] 发货单生成拣货单，完善 缺货 订单处理；完善测试数据

- good_shop/__manifest__.py
- good_shop/controllers/main.py
- good_shop/data/data.xml
- good_shop/views/good_shop_templates.xml
- warehouse/data/warehouse_demo.xml
- warehouse/models/goods.py
- warehouse/models/location.py
- warehouse/models/warehouse_move.py
- warehouse/view/warehouse_view.xml
- warehouse_wave/models/wave.py
- warehouse_wave/report/report.xml
- warehouse_wave/security/ir.model.access.csv
- warehouse_wave/tests/test_wave.py
> [ADD] 按 库位 就近原则生成拣货单，并完善测试数据

- warehouse/models/goods.py
- warehouse/models/location.py
- warehouse/models/warehouse_move_line.py
- warehouse/tests/__init__.py
- warehouse/tests/test_location.py
- warehouse/view/warehouse_view.xml
> [ADD] 实现 库位间 商品数量 转移；需要完善测试数据

- backend_theme/views/web.xml
> [IMP]打印页面时不显示左侧区块

- core/views/core_templates.xml
- core/views/core_view.xml
- money/models/money_order.py
- staff/views/leave.xml
- staff/views/staff.xml
- warehouse/menu/warehouse_menu.xml
> GoodERP issue #1438, # 1439, # 1441

- auto_exchange/models/auto_exchange.py
- backend_theme/static/src/less/main.less
- buy/models/buy_order.py
- buy/views/buy_order_view.xml
- buy/views/buy_receipt_view.xml
- sell/models/sell_order.py
- sell/views/sell_view.xml
- warehouse_wave/models/wave.py
- warehouse_wave/report/report.xml
- warehouse_wave/static/src/js/warehouse_wave_widget.js
- warehouse_wave/views/wave.xml
- web_stock_query/static/src/xml/query.xml
> gooderp测试中发现的几个问题修复

- sell/views/sell_view.xml
> [IMP] 发货单 tree 视图显示调出仓，可以按调出仓分组查看

- buy/views/buy_receipt_view.xml
- sell/views/sell_view.xml
- warehouse/models/warehouse_move.py
- warehouse_wave/models/express_menu.py
- warehouse_wave/models/wave.py
>  [UPD] 所有仓库业务支持快递；发货单显示快递信息，入库单tree显示经办人

- README.md
- home_page/models/home_page.py
- money/views/money_order_view.xml
> [IMP]结算单列表去掉删除功能

- buy/models/buy_receipt.py
- buy/views/buy_receipt_view.xml
- task/views/views.xml
> [FIX] 采购入库单添加运费；去掉任务tree上的editable

- asset/views/asset.xml
- core/views/core_view.xml
- finance/views/finance_conf.xml
- good_process/views/good_process.xml
- goods/view/goods_view.xml
- staff/views/staff.xml
- task/views/views.xml
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
> 主数据列表上的active字段无需显示

- account_cost/tests/test_cost_order.py
- buy/models/buy_order.py
- buy/models/buy_receipt.py
- buy/tests/test_buy_adjust.py
- buy/tests/test_buy_order.py
- buy/tests/test_report.py
- ir_sequence_autoreset/ir_sequence.py
- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/tests/test_sell_delivery.py
- sell/tests/test_sell_order.py
- sell/views/sell_view.xml
- staff/models/staff.py
- staff/views/staff.xml
- warehouse_wave/tests/test_wave.py
>  [ADD] 自动编号重置模块有权限问题 #1428

- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/views/sell_view.xml
- warehouse_wave/models/express_menu.py
- warehouse_wave/views/express_menu.xml
> [FIX] 发货单地址修改，快递面单收件人地址取联系人的省、市、县地址

- README.md
> 可能是中国用户数最多的开源ERP

- warehouse_wave/views/express_menu.xml
> [ADD] 去掉 wave 继承发货单显示的承运商和单号

- buy/models/buy_receipt.py
- sell/models/sell_delivery.py
> [IMP] 其他出库单，其他入库单不走这两个流程

- auto_exchange/models/auto_exchange.py
> [FIX]中行获取汇率的网页编码转化

- web_error_dialog/static/src/js/dialog.js
> [IMP]报错时有提示音

- warehouse/models/warehouse_move.py
- warehouse/models/warehouse_move_line.py
> [IMP]建议库位的逻辑放在移库单行上

- warehouse_wave/data/data.xml
- warehouse_wave/models/express_menu.py
- web_export_view_good/__openerp__.py
> [FIX]kdniao的utf-8编码支持

- buy/__openerp__.py
> [FIX] #1478 Buy模块应依赖地址模块

- warehouse_wave/static/src/js/warehouse_wave_widget.js
> [UPD] 快递面单+装箱单 打印分页

- warehouse_wave/data/data.xml
> [IMP]不要更新接口参数数据

- core/models/core.py
- money/models/money_order.py
- money/views/money_order_view.xml
> [IMP]增加单据作废功能，只实现了收付款单作废，其他单据据此修改

- warehouse_wave/models/express_menu.py
- warehouse_wave/models/wave.py
> [REF]用urllib2获取快递鸟面单

- warehouse_wave/report/report.xml
> [IMP]调整拣货单格式

- warehouse_wave/models/express_menu.py
- warehouse_wave/report/report.xml
- warehouse_wave/tests/test_wave.py
> [IMP]补足测试数据

- warehouse_wave/report/report.xml
- warehouse_wave/static/src/js/warehouse_wave_widget.js
- web_error_dialog/static/src/js/dialog.js
> [IMP]拣货单字体增大

- finance/models/issue_cost_wizard.py
- money/models/money_order.py
- warehouse/models/res_company.py
> [FIX]精度问题造成的成本月结报错

- core/models/res_company.py
- core/views/core_view.xml
> [REF]公司界面重写导致第三方模块无法使用 close #1503

- buy/models/buy_adjust.py
> [添加]采购变更单上加已作废状态

- buy/views/buy_receipt_view.xml
- sell/models/sell_order.py
- sell/views/sell_view.xml
> [UPD] 销售订单添加付款方式字段；采购入库单、销售发货单订单号加组、某些字段debug科技

- sell/models/partner.py
> [FIX] 修复点击客户中的购货记录出现的BUG

- warehouse/report/report_data.xml
> 仓库单据打印，去掉states限制

- core/models/goods.py
- core/models/res_company.py
- finance/models/issue_cost_wizard.py
- finance/wizard/checkout_wizard.py
- finance/wizard/checkout_wizard.xml
- goods/view/goods_view.xml
> [IMP]发出成本的计算方法 #1454

- buy/models/buy_order.py
- sell/models/sell_order.py
> [IMP]反审核订单时清空已执行数量

- buy/models/partner.py
- buy/views/vendor_goods_view.xml
- sell/models/partner.py
- sell/views/customer_view.xml
> [IMP] 销售和采购的购货记录时间为一年

- money/report/bank_statements_view.xml
> [ADD]关于资金单报表的功能完善 #1522

- backend_theme/__openerp__.py
- backend_theme/static/src/less/main.less
- core/static/src/js/core.js
- core/static/src/less/core.less
- core/static/src/xml/base.xml
- web_export_view_good/__openerp__.py
> [IMP]界面调整，去掉不必要的修饰

- sell_delivery_by_parts/__init__.py
- sell_delivery_by_parts/__openerp__.py
- sell_delivery_by_parts/models/__init__.py
- sell_delivery_by_parts/models/sell_delivery_by_parts.py
- sell_delivery_by_parts/views/sell_delivery_parts_view.xml
> [ADD] 添加 sell_delivery_by_parts #1539 模块，实现销售组合产品时自动出货子产品的功能

- asset/__manifest__.py
- asset/data/asset_demo.xml
- asset/data/home_page.xml
- asset/models/asset.py
- asset/views/asset.xml
- asset/views/asset_menu.xml
> asset 固定资产模块代码走查

- asset/models/asset.py
> 固定资产变更后的月折旧额计算 #1550

- asset/models/asset.py
- buy/views/buy_receipt_view.xml
- sell/models/sell_delivery.py
- sell/wizard/sell_order_track_wizard.py
- warehouse/models/warehouse_move_line.py
> [ADD] 月底提折旧，生成的凭证是最后一个资产的折旧 #1548

- asset/models/asset.py
- sell/models/sell_delivery.py
> [FIX] [ADD] 月底提折旧，生成的凭证是最后一个资产的折旧 #1548

- money/report/bank_statements.py
- money/report/customer_statements.py
- money/report/supplier_statements.py
> [FIX] 修复现金银行报表、客户/供应商对账单报表，数据量比较大报错

- account_cost/__openerp__.py
- money/models/money_order.py
- money/tests/test_money.py
收付款金额可以输入负数，此时并没有核销行存在，不应报错
---
提交前:
---
提交后:
---
--
> [IMP]支持在交易发生前退预收款

- good_process/models/mail_thread.py
- good_process/views/good_process.xml
- money/wizard/bank_statements_wizard.py
- sell/report/sell_summary.py
- sell/report/sell_summary_view.xml
- warehouse/models/warehouse_move.py
>  [ADD] 审批流设置增加一个适用条件的domain字段 #1501

- core/controllers/controllers.py
> [FIX] url登录调用function的方法有误

- warehouse/models/warehouse_move_line.py
> [IMP]只在属性输入的时候考虑属性

- core/models/goods.py
> [ADD] 关于开单选择货品的bug #1511

- buy/report/buy_order_track.py
- buy/report/buy_order_track_view.xml
- buy/wizard/buy_order_track_wizard.py
- core/models/goods.py
- report_docx/report/report_docx.py
- sell/report/sell_order_track.py
- sell/report/sell_order_track_view.xml
- sell/views/sell_view.xml
- sell/wizard/sell_order_track_wizard.py
> 销售单默认过滤“我的订单” #1572; 点击打印按钮可追溯 #1580 

- core/models/partner.py
- core/tests/test_core.py
- money/tests/test_reconcile_order.py
- report_docx/report/report_docx.py
- warehouse/report/lot_status.py
- warehouse/report/lot_status_view.xml
> [ADD] 关于业务伙伴科目余额不为0的时候 不允许取消对应的客户/供应商身份 #1570

- buy/models/buy_adjust.py
- buy/models/buy_order.py
- buy/tests/test_buy_adjust.py
- buy/tests/test_buy_order.py
- sell/models/sell_adjust.py
- sell/models/sell_order.py
- sell/report/sell_order_detail.py
- sell/report/sell_order_detail_view.xml
- sell/tests/test_sell_adjust.py
- sell/tests/test_sell_delivery.py
- sell/tests/test_sell_order.py
- sell/wizard/sell_order_detail_wizard.py
- sell_quotation/views/sell_quotation_view.xml
- staff/models/staff_contract.py
- staff/tests/test_staff.py
- staff/views/staff.xml
- warehouse/models/warehouse_move_line.py
>  [ADD] 销售明细表增加单据的结算字段 #1585  员工社保应该用比例而非绝对值 #1381

- buy/wizard/buy_order_detail_wizard.py
- buy/wizard/buy_order_track_wizard.py
- buy/wizard/buy_payment_wizard.py
- buy/wizard/buy_summary_goods_wizard.py
- buy/wizard/buy_summary_partner_wizard.py
- sell/wizard/sell_order_detail_wizard.py
- sell/wizard/sell_order_track_wizard.py
- sell/wizard/sell_receipt_wizard.py
- sell/wizard/sell_summary_goods_wizard.py
- sell/wizard/sell_summary_partner_wizard.py
- sell/wizard/sell_summary_staff_wizard.py
- sell/wizard/sell_top_ten_wizard.py
> [IMP] 根据群里意见，把 help “按指定……进行统计” 修改为 “只统计选定的……”

- buy/models/buy_adjust.py
- buy/models/buy_order.py
- sell/models/sell_adjust.py
- sell/models/sell_order.py
- warehouse/models/warehouse_move_line.py
>  [FIX] 去掉 不含税单价的 自动计算属性

- money/models/money_order.py
- money/wizard/partner_statements_wizard.py
- money/wizard/partner_statements_wizard_view.xml
> [ADD]核销单核销单据的时候 选的是核销单的日期对应的会计区间，不是核销的单据的会计区间 #1591

- buy/tests/test_buy_order.py
- buy/tests/test_supplier_statements.py
- finance/tests/test_finance.py
- sell/tests/test_finance.py
- sell/tests/test_sell_order.py
- sell_quotation/__openerp__.py
- sell_quotation/data/demo.xml
- sell_quotation/models/sell_quotation.py
- sell_quotation/tests/__init__.py
- sell_quotation/tests/test_sell_quotation.py
- warehouse_wave/models/wave.py
- warehouse_wave/static/src/js/warehouse_wave_widget.js
>  [ADD] 添加 报价单、业务伙伴查看购货记录 测试数据

- sell_quotation/views/sell_quotation_view.xml
> [ADD] 关于选用报价单系统后，是否可以在订单行里不显示折扣 #1598

- auto_exchange/__openerp__.py
- auto_exchange/tests/__init__.py
- auto_exchange/tests/demo.xml
- auto_exchange/tests/test_auto_exchange.py
- buy/models/buy_order.py
- sell/models/sell_order.py
- warehouse/models/production.py
> [ADD] 包含了产品属性的物料清单在委外加工单中选择后不能在组合件和子件中自动显示属性 #1603

- warehouse/models/production.py
- warehouse/models/res_company.py
- warehouse/models/warehouse_move_line.py
- warehouse/view/production_view.xml
- warehouse/view/res_company.xml
> [ADD] 委外加工单中如何录入委外产生的废品 #1604

- buy/models/partner.py
- core/static/src/js/core.js
- sell/models/partner.py
> FIX #1601 扫描控件没有默认获得焦点

- auto_backup/data/backup_demo.xml
- auto_backup/tests/test_backup.py
- core/models/core.py
- core/views/core_view.xml
- goods/models/goods_class.py
- goods/tests/test_goods.py
- money/views/partner_view.xml
- staff/tests/test_staff.py
> [ADD] 添加 auto_backup 测试数据

- buy/wizard/supplier_statements_wizard_view.xml
- money/models/partner.py
- money/tests/test_ReportDocxPartner.py
- money/tests/test_money.py
- sell/wizard/customer_statements_wizard_view.xml
- staff_wages/report/wages_templates.xml
- warehouse_wave/tests/test_wave.py
> [ADD] 既是客户又是供应商的业务伙伴，在供应商 tree 视图点击 查看对账单 放大镜，显示的是客户对账单，存在 bug

- buy/models/buy_receipt.py
- buy/report/supplier_statements.py
- money/models/money_order.py
- money/report/customer_statements.py
- money/report/supplier_statements.py
- sell/report/customer_statements.py
- warehouse/models/warehouse_move_line.py
- warehouse/tests/test_goods.py
- warehouse/tests/test_move_line.py
- warehouse/tests/test_production.py
- warehouse/tests/test_warehouse.py
>  [ADD] 应收冲应付的核销单审核后对应业务伙伴的应收应付金额都未减少 #1620

- partner_address/models/partner_address.py
- warehouse/action/warehouse_action.xml
- web_stock_query/static/src/js/query.js
> [IMP]修复库存余额表列表和透视图条目不符

- core/models/core.py
- good_crm/tests/__init__.py
- good_crm/tests/test_good_crm.py
- money/models/money_transfer_order.py
- money/tests/test_money.py
> [FIX] 资金转账单 反审核时删除凭证 bug

- warehouse_wave/report/report.xml
> [ADD] #IHCXP 拣货单打印时相同产品的格子号升序排列

- buy/tests/test_buy_order.py
- sell/tests/test_sell_delivery.py
- sell/tests/test_sell_order.py
- sell_delivery_by_parts/models/sell_delivery_by_parts.py
- sell_delivery_by_parts/tests/__init__.py
- sell_delivery_by_parts/tests/test_sell_delivery_by_parts.py
- warehouse/tests/test_production.py
> [UPD] 添加 sell_delivery_by_parts 测试数据

- asset/tests/test_asset.py
- auto_exchange/models/auto_exchange.py
- auto_exchange/tests/demo.xml
- auto_exchange/tests/test_auto_exchange.py
- sell/tests/test_sell_order.py
- warehouse_wave/tests/test_wave.py
> [UPD] 添加 auto_exchange 测试数据

- finance/models/issue_cost_wizard.py
- finance/tests/test_finance.py
- scm/tests/test_good_process.py
- warehouse/tests/test_inventory.py
- warehouse/tests/test_warehouse_order.py
- warehouse_wave/tests/test_wave.py
> [ADD] 添加测试数据

- auto_backup/data/backup_demo.xml
- buy/report/buy_order_track_view.xml
- buy/report/buy_summary_goods_view.xml
- buy/report/buy_summary_partner_view.xml
- buy/views/buy_order_view.xml
- buy/views/buy_receipt_view.xml
- buy/wizard/buy_payment_wizard.py
- goods/view/goods_view.xml
- money/report/bank_statements_view.xml
- money/views/money_transfer_order_view.xml
- money/views/reconcile_order_view.xml
- sell/views/sell_view.xml
- staff/views/staff.xml
- task/views/views.xml
- warehouse/report/lot_status_view.xml
- warehouse/report/stock_balance_view.xml
- warehouse/report/stock_transceive.py
- warehouse/view/production_view.xml
- warehouse/view/warehouse_view.xml
- warehouse/wizard/non_active_report_wizard.xml
> [IMP]列表字段调整

- warehouse/view/warehouse_view.xml
> [FIX]sum属性重复

- .travis.yml
- auto_backup/data/backup_demo.xml
- auto_backup/models/backup_scheduler.py
- auto_backup/tests/test_backup.py
> [ADD] 添加自动备份测试数据

- sell/models/sell_adjust.py
> [IMP]销售调整单的当调整一行是，不会删除出货分单

- buy/models/buy_receipt.py
- buy/tests/test_buy_receipt.py
- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/tests/test_sell_delivery.py
- staff_expense/__manifest__.py
- staff_expense/tests/__init__.py
- staff_expense/tests/staff_expense_demo.xml
- staff_expense/tests/test_hr_expense.py
> [FIX] 修改销货单地址，地址下拉列表有误的问题 #1651

- money/data/money_data.xml
- sell/models/sell_delivery.py
> [IMP]使用write避免写入失败

- core/models/goods.py
- warehouse_wave/models/express_menu.py
> [IMP]如果产品名称里有特殊字符，包括' " # & + < >，快递鸟会报错，验证数据签名失败

- warehouse_wave/models/express_menu.py
- warehouse_wave/tests/test_express_menu.py
> [IMP]拣货单号放在手机号码位置造成报错

- buy/models/buy_order.py
- sell/models/sell_order.py
> [IMP]采购单销售单增加数量合计字段

- asset/tests/test_asset.py
- core/models/core.py
- core/tests/test_core.py
- finance/data/finance_data.xml
- money/data/money_data.xml
- sell/views/sell_view.xml
- warehouse/view/production_view.xml
> 系统创建的类别不应该删 #1687

- good_process/models/mail_thread.py
- good_process/views/good_process.xml
- money/models/partner.py
- money/report/money_get_pay.py
- money/report/money_get_pay_view.xml
> [ADD] 资金收支报表应显示含税金额 #1692

- goods/action/goods_action.xml
- goods/menu/goods_menu.xml
- goods/view/goods_view.xml
> [ADD] 添加 SKU 菜单

- goods/menu/goods_menu.xml
- goods/view/goods_view.xml
- warehouse/models/production.py
- warehouse/wizard/non_active_report_wizard.py
- warehouse/wizard/non_active_report_wizard.xml
> [IMP] SKU 菜单添加 group_no_one

- warehouse/models/location.py
- warehouse_wave/models/express_menu.py
> [FIX] 转出库位与转入库位的 产品、产品属性要相同:转入库位产品可以为False; 快递面单打印收件人地址信息优化

- buy/views/buy_receipt_view.xml
- finance/models/finance.py
- finance/models/voucher_template.py
- goods/models/goods.py
- partner_address/models/partner_address.py
- staff/tests/staff_demo.xml
- staff/tests/test_staff.py
- task/data/data.xml
- task/demo/demo.xml
- task/models/task.py
- task/views/views.xml
>  同一属性的值不能重复；属性的值应该必输 #1685　 辅助核算项的名称、编码、分类都不能为空＃1661 ＃1660 #1659

- buy/models/buy_receipt.py
- sell/models/sell_delivery.py
> [IMP]退货的同时也已退款，不生成新的分单

- finance/models/finance.py
> [FIX]辅助核算编码不需要必输

- sell_quotation/models/sell_quotation.py
> [FIX] 报价单和销售订单，价格的小数精度不一致 #1722

- staff_hire/__manifest__.py
- staff_hire/data/hire_data.xml
- staff_hire/models/staff_hire.py
- staff_hire/report/hire_report_view.xml
- staff_hire/security/ir.model.access.csv
- staff_hire/views/hire_view.xml
- staff_hire/views/staff_job_view.xml
> [FIX]修改csv，去掉招聘菜单的组

- warehouse/models/location.py
- warehouse_wave/models/wave.py
- warehouse_wave/report/report.xml
> [FIX] 拣货单打印时间取成 系统当前时间；库位数量赋值写法修改

- staff/views/staff.xml
- staff_hire/models/staff_hire.py
- staff_hire/models/staff_job.py
- staff_hire/views/hire_view.xml
- staff_survey/__manifest__.py
- staff_survey/views/hire_applicant_view.xml
> [FIX]招聘form上能跳到指定员工界面上，职位界面上点击员工按钮也能正确跳转，招聘看板视图修改等

- warehouse/models/move_matching.py
- warehouse/models/production.py
- warehouse/models/warehouse_move.py
- warehouse/models/warehouse_move_line.py
- warehouse/report/stock_balance.py
- warehouse/tests/test_move_line.py
> [IMP] 作废相关单据时，可以作废move line；原 action_cancel 更名为 action_draft

- core/static/src/js/core.js
- core/static/src/xml/base.xml
- core/views/core_view.xml
> [FIX]增加菜单更多应用

- warehouse/models/production.py
> [ADD]组合件和子件不能相同#1686

- warehouse_wave/models/express_menu.py
> [ADD] 打印快递面单、装箱单，按 move 上的格子号排序

- warehouse_wave/models/express_menu.py
> [ADD] 按格子号排序写法修改

- buy/models/buy_order.py
- buy/models/buy_receipt.py
- buy/views/buy_order_view.xml
- buy/views/buy_receipt_view.xml
- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/views/sell_view.xml
> [ADD]采购销售单据上对于有本次收款/付款的关联收付款单号 #1668

- goods/models/goods_class.py
> [IMP]产品分类的类型是节点或者常规

- home_page/static/src/css/home_page.css
- home_page/static/src/js/home_page.js
> [IMP]首页，乱改一气

- core/models/partner.py
- core/views/core_view.xml
- warehouse/models/warehouse_move.py
- warehouse/view/production_view.xml
> [FIX]组装单、拆卸单、委外单按钮状态优化 #1697

- core/tests/test_core.py
- staff/tests/test_staff.py
- warehouse_wave/models/wave.py
- warehouse_wave/tests/test_wave.py
>  [IMP] 添加 wave 测试数据

- core/models/partner.py
- sell/report/sell_receipt.py
- sell/report/sell_receipt_view.xml
- sell/wizard/sell_receipt_wizard.py
> [FIX]销售收款一览表bug：未考虑客户预收款情况 #1708

- .travis.yml
- asset/data/asset_data.xml
- finance/data/finance_data.xml
- finance/models/balance_sheet.py
- finance/models/finance.py
- finance/security/ir.model.access.csv
- finance/tests/finance_demo.xml
- finance/views/finance_conf.xml
- money/tests/test_money.py
> [IMP]1001没有下级

- home_page/static/src/xml/homepage.xml
---
修正“主要功能”水平不居中
提交前:
---
提交后:
---
--
> “主要功能”align-center修正

- sell/report/sell_order_detail_view.xml
> 销售明细表报表添加产品名称搜索

- warehouse_wave/models/express_menu.py
> [ADD] 打印快递面单 详细地址 去除重复的省、市、县等

- core/views/core_view.xml
- finance/models/finance.py
- sell/views/sell_view.xml
> [FIX]升级版本失败 #1774

- finance/views/finance_conf.xml
> [IMP]旧数据库升级后需要修改会计要素和上级科目

- core/models/partner.py
- finance/models/finance.py
> [IMP]可以按编码搜到唯一的客户、供应商或会计科目

- warehouse/models/location.py
> [IMP] 当前数量为0，清空库位上的商品和属性，写法修改

- warehouse/models/inventory.py
> [FIX] 盘点 明细行 问题

- finance/tests/test_finance.py
- finance/wizard/checkout_wizard.py
> [IMP]按月编号也要检查上一期间已结账

- warehouse_wave/security/ir.model.access.csv
> [IMP] wave 预留表权限修改

- finance/models/finance.py
- finance/tests/test_finance.py
> [IMP] 如果对应会计期间不存在，则创建。去掉报错提醒

- buy/report/supplier_statements.py
- finance/models/finance.py
- money/models/money_order.py
- money/report/customer_statements.py
- money/report/supplier_statements.py
- sell/report/customer_statements.py
> [ADD] 应收转应收结果有问题 #1691

- warehouse/models/goods.py
- warehouse/tests/test_goods.py
>  关于商品单位的bug #1787

- report_docx/report/report_docx.py
- warehouse/models/goods.py
> [FIX]docx文档打印时，如内容包含 & 符号会报错 #1543

- finance/models/balance_sheet.py
- finance/models/finance.py
> [FIX] 利润表修改

- account_cost/models/cost_order.py
- buy/models/buy_receipt.py
- buy/tests/test_buy_receipt.py
- buy/tests/test_report.py
- buy/tests/test_supplier_statements.py
- finance/models/finance.py
- finance/models/trial_balance.py
- good_process/models/mail_thread.py
- money/models/money_order.py
- money/tests/test_invoice.py
- money/tests/test_money.py
- money/tests/test_reconcile_order.py
- scm/models/stock_request.py
- sell/models/sell_delivery.py
- sell/tests/test_finance.py
- sell/tests/test_report.py
- staff_expense/models/hr_expense.py
- staff_hire/models/staff_hire.py
- staff_hire/models/staff_job.py
- staff_wages/models/staff_wages.py
- warehouse/models/inventory.py
- warehouse/models/production.py
- warehouse/models/warehouse_move.py
- warehouse/tests/test_report.py
- warehouse/tests/test_warehouse_order.py
> [FIX]所有单据在确认时检查状态

- money/models/money_order.py
> [ADD] 批量修改结算单到期日 #1796

- buy/views/buy_action.xml
- buy/views/buy_receipt_view.xml
- good_crm/views/crm_view.xml
- sell/views/sell_view.xml
- staff/views/leave.xml
- staff_hire/views/hire_view.xml
- task/views/views.xml
> [ADD]商机、收发货单加日历视图 #1799

- finance/wizard/checkout_wizard.py
> [IMP]月末结转向导最后应该返回收入转利润的凭证 #1688

- money/models/money_order.py
- web_export_view_good/static/src/js/web_export_view_good.js
> [FIX] 报表打印 合计行错位问题修复；合计行数字靠右显示；报表打印，负数符号问题修复

- cn_account_invoice/models/cn_account_invoice.py
- tax_invoice_out/models/tax_invoice_out.py
> [FIX]销售发票导入excel时的问题，及其他

- goods/tests/test_goods.py
> [ADD] 添加 goods get_tax_rate 测试数据

- buy/wizard/buy_payment_wizard.py
- sell/wizard/sell_receipt_wizard.py
> [FIX]修改采购付款和销售收款一览表收款金额计算逻辑

- staff_hire/models/staff_job.py
- staff_hire/tests/__init__.py
- staff_hire/tests/test_staff_job.py
- staff_survey/__manifest__.py
- staff_survey/models/hire_applicant.py
- staff_survey/tests/__init__.py
- staff_survey/tests/demo.xml
- staff_survey/tests/test_hire_applicant.py
> [ADD]增加staff_job.py测试及加上方法注释

- staff_wages/tests/test_staff_wages.py
- warehouse_wave/tests/test_express_menu.py
> [IMP] 添加 wave 收件人详细地址处理相关测试数据

- sell/models/sell_order.py
- sell/tests/test_report.py
- sell/tests/test_sell_delivery.py
- sell/tests/test_sell_order.py
> [ADD]增加sell_receipt和sell_order.py测试

- account_cost/tests/test_cost_order.py
- app_odoo_customize/models/ir_ui_view.py
- asset/tests/test_asset.py
- auto_exchange/models/auto_exchange.py
- auto_exchange/tests/test_auto_exchange.py
- buy/models/buy_receipt.py
- buy/tests/test_buy_order.py
- buy/tests/test_buy_receipt.py
- buy/views/buy_adjust_view.xml
- buy/views/buy_order_view.xml
- buy/views/buy_receipt_view.xml
- core/models/goods.py
- goods/view/goods_view.xml
>  [IMP] 完善测试数据，也会优化相关代码的写法

- finance/models/balance_sheet.py
- finance/models/exchange.py
- finance/models/finance.py
- finance/tests/test_exchange.py
- finance/tests/test_finance.py
> [IMP] finance 提高测试覆盖率

- finance/tests/test_finance.py
> [IMP] finance 一次只能为一个科目增加下级

- cn_account_invoice/tests/test_cn_account_invoice.py
- core/tests/test_core.py
> [IMP] 添加 cn_account_invoice 测试数据

- buy/tests/test_buy_receipt.py
- goods/tests/test_goods.py
- money/tests/test_invoice.py
- money/tests/test_money.py
- sell/tests/test_sell_order.py
- warehouse/models/production.py
- warehouse/models/warehouse_move_line.py
- warehouse/tests/test_production.py
> [ADD]增加覆盖率：sell_order,money模块相关文件

- goods/tests/test_goods.py
- sell/security/rules.xml
> [IMP] 添加 core 模块 goods.py 测试数据

- sell/tests/test_sell_delivery.py
- warehouse/models/warehouse_move.py
- warehouse/models/warehouse_move_line.py
- warehouse/tests/test_goods.py
- warehouse/tests/test_location.py
- warehouse/tests/test_move_line.py
- warehouse/tests/test_warehouse_order.py
> [ADD]为warehouse 增加测试

- warehouse/models/production.py
> [FIX] 从物料清单创建组装单，辅助数量不会更新BUG #1835

- finance/models/trial_balance.py
- finance/tests/test_report.py
- warehouse/report/stock_balance_view.xml
> [IMP] 添加 trial balance 调整累计 相关测试；代码优化

- buy/models/buy_receipt.py
- ir_sequence_autoreset/tests/__init__.py
- ir_sequence_autoreset/tests/test_ir_sequence.py
- sell/tests/test_sell_delivery.py
- warehouse/tests/test_inventory.py
> 增加测试；[FIX]购货订单按收货结算时，对应入库单的付款状态没有更新

- scm/tests/test_scm.py
- warehouse/data/warehouse_demo.xml
- warehouse/models/inventory.py
- warehouse/models/warehouse_order.py
- warehouse/tests/test_inventory.py
- warehouse/tests/test_warehouse_order.py
> [ADD]增加测试，warehouse相关代码修改

- warehouse/models/warehouse_order.py
- warehouse/tests/test_location.py
- warehouse/tests/test_move_line.py
- warehouse/tests/test_production.py
- warehouse/tests/test_warehouse.py
- warehouse/tests/test_warehouse_order.py
- warehouse_wave/tests/test_express_menu.py
> [ADD]增加wh_move_line warehouse_order测试

- money/report/supplier_statements.py
- sell/tests/test_ReportDocx.py
- sell_to_buy/__init__.py
- sell_to_buy/__manifest__.py
- sell_to_buy/models/__init__.py
- sell_to_buy/models/buy.py
- sell_to_buy/models/sell.py
- sell_to_buy/views/buy_view.xml
- sell_to_buy/wizard/__init__.py
- sell_to_buy/wizard/sell_to_buy_wizard.py
- sell_to_buy/wizard/sell_to_buy_wizard_view.xml
- warehouse/tests/test_non_active_report.py
- warehouse_wave/models/wave.py
- warehouse_wave/tests/test_wave.py
> [ADD]增加wave及warehouse 呆滞料报表测试

- buy/models/buy_receipt.py
- money/models/money_order.py
- warehouse/models/warehouse_move_line.py
> [FIX]未确认的结算单，会出现在收/付款单的结算单列表中 #1860

- warehouse_wave/models/wave.py
>  [IMP] 生成拣货单时，库存不足，报错提示相关发货单

- asset/models/asset.py
- money/models/money_order.py
- sell_to_buy/models/buy.py
- sell_to_buy/models/sell.py
- sell_to_buy/views/buy_view.xml
- sell_to_buy/wizard/sell_to_buy_wizard.py
- sell_to_buy/wizard/sell_to_buy_wizard_view.xml
> [FIX]sell_to_buy:购货订单行增加sell_line_id，删除时去掉对应销货单行的已采购打勾 #1857

- buy/views/buy_receipt_view.xml
- finance/tests/test_finance.py
- finance/tests/test_report.py
- sell/views/sell_view.xml
- warehouse/models/goods.py
- warehouse/models/move_matching.py
- warehouse/report/stock_balance.py
- warehouse/report/stock_balance_view.xml
- warehouse/view/warehouse_view.xml
- warehouse_wave/models/wave.py
> [IMP] 完善相关逻辑，出库时可以选择出库库位；库存余额表优化；代码优化

- buy/models/buy_adjust.py
- buy/models/buy_order.py
- buy/tests/test_buy_adjust.py
- buy/tests/test_buy_order.py
- buy/tests/test_report.py
- money/models/money_order.py
- scm/models/stock_request.py
- sell/models/sell_adjust.py
- sell/models/sell_order.py
- sell/tests/test_sell_delivery.py
- sell_to_buy/models/buy.py
- warehouse/models/warehouse_move_line.py
- warehouse/tests/test_inventory.py
- warehouse_wave/tests/test_wave.py
>  [IMP]关于批次、属性权限控制问题 #1865：保存时做限制

- buy/models/buy_adjust.py
- buy/tests/test_buy_adjust.py
- sell/models/sell_adjust.py
- warehouse/tests/test_move_line.py
> [FIX]增加测试，变更单审核时检查属性是否填充

- buy/tests/test_buy_order.py
- sell/tests/test_sell_adjust.py
- sell/tests/test_sell_order.py
- sell_to_buy/models/buy.py
- sell_to_buy/models/sell.py
- sell_to_buy/tests/__init__.py
- sell_to_buy/tests/test_buy.py
- sell_to_buy/tests/test_wizard.py
- sell_to_buy/wizard/sell_to_buy_wizard.py
> [ADD]增加sell_to_buy测试及其他测试

- money/models/money_order.py
> [FIX] 核销单的应收冲应付没有生成结算单 #1866

- buy/models/buy_receipt.py
- goods_code/__init__.py
- goods_code/__manifest__.py
- goods_code/models/__init__.py
- goods_code/models/goods.py
- money/models/partner.py
- sell/models/sell_delivery.py
- sell/tests/test_sell_delivery.py
- sell_to_buy/models/sell.py
- sell_to_buy/views/buy_view.xml
> 测试及其他[FIX]修改业务伙伴期初设置，改为0时也需删除以前的结算单

- good_process/models/mail_thread.py
- warehouse/tests/test_goods.py
> [FIX]修复bug:付款单设置了审批流程但入库单审核生成的付款单审批流程没加上； add test

- buy/models/buy_receipt.py
- good_process/models/mail_thread.py
- sell/models/sell_delivery.py
> [FIX]1.审批向导进去所有单据跳过审批的bug，2.不需审批单据自动移除待审批人，3.作废单据时做判断

- good_process/models/mail_thread.py
> [FIX]修复作废时只能移除第一个审批组的bug，作废时应全部移除待审批人

- sell/models/sell_order.py
- sell/tests/test_sell_order.py
> [ADD]销货订单上增加净重合计及添加测试

- money/report/customer_statements.py
- money/report/supplier_statements.py
> [FIX]业务伙伴对账单应收/应付余额涉及到折扣时计算的bug

- buy/models/buy_receipt.py
> [FIX]关于批次号的收货的bug #1887:入库单生成退货单时不该传入lot_id

- money/tests/test_invoice.py
- partner_address/views/partner_address.xml
- sell/models/sell_delivery.py
- sell/models/sell_order.py
- sell/views/sell_view.xml
>  销售单默认取客户对应的业务员 否则就是取开单人员

- money/models/money_order.py
> 升级反核销资金单逻辑

- warehouse_wave/models/express_menu.py
> [ADD] 打印圆通快递面单换成三联单

- money/models/generate_accounting.py
- money/models/partner.py
> [FIX]解决客户和供应商双重身份的期初问题等

- sell/models/sell_delivery.py
> 退货不能获取采购成本

- core/static/src/xml/base.xml
停止：
- SAAS在线服务
- 二次开发服务
- 远程支持服务
> [Bye]去掉服务及广告

- core/static/src/xml/base.xml
- warehouse/tests/test_report.py
> 库存收发明细表many2one记录商品
